import json, os

locales_dir = os.path.join(os.path.dirname(__file__), "public", "locales")

# All translations keyed by language code
translations = {
    "hi": {
        "nav": {"overview":"अवलोकन","workspace":"विश्लेषण कार्यक्षेत्र","results":"परिणाम","history":"विश्लेषण इतिहास","models":"मॉडल और उपकरण","datasets":"डेटासेट","reports":"रिपोर्ट","settings":"सेटिंग्स","navigation":"नेविगेशन","systemStatus":"सिस्टम स्थिति","aiEngine":"AI इंजन","geoPipeline":"जियो पाइपलाइन","dataLink":"डेटा लिंक","analyst":"विश्लेषक","systemOnline":"सिस्टम ऑनलाइन","syncAgo":"0 मिनट पहले सिंक","utc":"UTC"},
        "workspace": {"title":"विश्लेषण कार्यक्षेत्र","ready":"AI अनुमान इंजन: तैयार","singleImage":"एकल छवि","objectDetection":"वस्तु पहचान","disasterAnalysis":"आपदा विश्लेषण","opticalSar":"ऑप्टिकल + SAR","biTemporal":"द्वि-कालिक","advanced":"उन्नत","image":"छवि","opticalImage":"ऑप्टिकल छवि","sarImage":"SAR छवि","beforeImage":"पूर्व छवि","afterImage":"बाद की छवि","uploadDesc":"खींचें और छोड़ें या अपलोड करने के लिए क्लिक करें","uploadFormats":"GeoTIFF · TIFF · PNG · JPEG · अधिकतम 2GB","disasterType":"आपदा प्रकार","targetClasses":"लक्ष्य वर्ग","selectAll":"सभी चुनें","deselectAll":"सभी हटाएं","disasterQuery":"आपदा प्रश्न","optionalQuery":"वैकल्पिक प्रश्न","askSatquery":"SatQuery से पूछें","queryPlaceholderDisaster":"उदा. भूस्खलन प्रभावित क्षेत्र पहचानें...","queryPlaceholderDetection":"उदा. इमारतें और वाहन पहचानें...","queryPlaceholderGeneral":"अपनी उपग्रह छवि के बारे में प्रश्न पूछें...","suggestions":"सुझाव","analyzeDisaster":"आपदा विश्लेषण करें","detectObjects":"वस्तु पहचानें","analyzeQuery":"प्रश्न विश्लेषण करें","analyzingDisaster":"आपदा विश्लेषण हो रहा है…","detecting":"पहचान हो रही है…","analyzing":"विश्लेषण हो रहा है…","viewer":"उपग्रह छवि दर्शक","showOverlays":"ओवरले दिखाएं","hideOverlays":"ओवरले छुपाएं","lat":"अक्षांश","lon":"देशांतर","zoom":"ज़ूम","resolution":"रिज़ॉल्यूशन","mode":"मोड","detections":"पहचान","disaster":"आपदा","severity":"गंभीरता","affectedArea":"प्रभावित क्षेत्र","agentTrace":"एजेंट निष्पादन ट्रेस","uploadImageFirst":"विश्लेषण शुरू करने के लिए छवि अपलोड करें और प्रश्न दर्ज करें","selectClassesFirst":"लक्ष्य वर्ग चुनें और वस्तु पहचानें पर क्लिक करें","selectDisasterFirst":"आपदा प्रकार चुनें और आपदा विश्लेषण पर क्लिक करें","processingMetadata":"मेटाडेटा प्रोसेस हो रहा है…"},
        "results": {"title":"विश्लेषण परिणाम","objectsDetected":"वस्तुएं","confidence":"विश्वास","loading":"मॉड्यूल लोड हो रहा है..."},
        "common": {"online":"ऑनलाइन","offline":"ऑफलाइन","error":"कुछ गलत हो गया","success":"सफल","warning":"चेतावनी","search":"भाषा खोजें..."}
    },
    "mr": {
        "nav": {"overview":"आढावा","workspace":"विश्लेषण कार्यक्षेत्र","results":"निकाल","history":"विश्लेषण इतिहास","models":"मॉडेल आणि साधने","datasets":"डेटासेट","reports":"अहवाल","settings":"सेटिंग्ज","navigation":"नेव्हिगेशन","systemStatus":"सिस्टम स्थिती","aiEngine":"AI इंजिन","geoPipeline":"जियो पाइपलाइन","dataLink":"डेटा लिंक","analyst":"विश्लेषक","systemOnline":"सिस्टम ऑनलाइन","syncAgo":"0 मिनिटांपूर्वी सिंक","utc":"UTC"},
        "workspace": {"title":"विश्लेषण कार्यक्षेत्र","ready":"AI अनुमान इंजिन: तयार","singleImage":"एकल प्रतिमा","objectDetection":"वस्तू ओळख","disasterAnalysis":"आपत्ती विश्लेषण","opticalSar":"ऑप्टिकल + SAR","biTemporal":"द्वि-कालिक","advanced":"प्रगत","image":"प्रतिमा","opticalImage":"ऑप्टिकल प्रतिमा","sarImage":"SAR प्रतिमा","beforeImage":"आधीची प्रतिमा","afterImage":"नंतरची प्रतिमा","uploadDesc":"ड्रॅग आणि ड्रॉप करा किंवा अपलोड करण्यासाठी क्लिक करा","uploadFormats":"GeoTIFF · TIFF · PNG · JPEG · कमाल 2GB","disasterType":"आपत्ती प्रकार","targetClasses":"लक्ष्य वर्ग","selectAll":"सर्व निवडा","deselectAll":"सर्व काढा","disasterQuery":"आपत्ती प्रश्न","optionalQuery":"पर्यायी प्रश्न","askSatquery":"SatQuery ला विचारा","queryPlaceholderDisaster":"उदा. भूस्खलन प्रभावित क्षेत्र ओळखा...","queryPlaceholderDetection":"उदा. इमारती आणि वाहने ओळखा...","queryPlaceholderGeneral":"तुमच्या उपग्रह प्रतिमेबद्दल प्रश्न विचारा...","suggestions":"सूचना","analyzeDisaster":"आपत्ती विश्लेषण करा","detectObjects":"वस्तू ओळखा","analyzeQuery":"प्रश्न विश्लेषण करा","analyzingDisaster":"आपत्ती विश्लेषण होत आहे…","detecting":"ओळख होत आहे…","analyzing":"विश्लेषण होत आहे…","viewer":"उपग्रह प्रतिमा दर्शक","showOverlays":"ओव्हरले दाखवा","hideOverlays":"ओव्हरले लपवा","lat":"अक्षांश","lon":"रेखांश","zoom":"झूम","resolution":"रिझोल्यूशन","mode":"मोड","detections":"ओळख","disaster":"आपत्ती","severity":"तीव्रता","affectedArea":"प्रभावित क्षेत्र","agentTrace":"एजंट अंमलबजावणी ट्रेस","uploadImageFirst":"विश्लेषण सुरू करण्यासाठी प्रतिमा अपलोड करा आणि प्रश्न प्रविष्ट करा","selectClassesFirst":"लक्ष्य वर्ग निवडा आणि वस्तू ओळखा वर क्लिक करा","selectDisasterFirst":"आपत्ती प्रकार निवडा आणि आपत्ती विश्लेषण वर क्लिक करा","processingMetadata":"मेटाडेटा प्रक्रिया होत आहे…"},
        "results": {"title":"विश्लेषण निकाल","objectsDetected":"वस्तू","confidence":"विश्वास","loading":"मॉड्यूल लोड होत आहे..."},
        "common": {"online":"ऑनलाइन","offline":"ऑफलाइन","error":"काहीतरी चुकले","success":"यशस्वी","warning":"चेतावणी","search":"भाषा शोधा..."}
    },
    "bn": {
        "nav": {"overview":"ওভারভিউ","workspace":"বিশ্লেষণ কর্মক্ষেত্র","results":"ফলাফল","history":"বিশ্লেষণ ইতিহাস","models":"মডেল ও সরঞ্জাম","datasets":"ডেটাসেট","reports":"প্রতিবেদন","settings":"সেটিংস","navigation":"নেভিগেশন","systemStatus":"সিস্টেম অবস্থা","aiEngine":"AI ইঞ্জিন","geoPipeline":"জিও পাইপলাইন","dataLink":"ডেটা লিঙ্ক","analyst":"বিশ্লেষক","systemOnline":"সিস্টেম অনলাইন","syncAgo":"০ মিনিট আগে সিঙ্ক","utc":"UTC"},
        "workspace": {"title":"বিশ্লেষণ কর্মক্ষেত্র","ready":"AI অনুমান ইঞ্জিন: প্রস্তুত","singleImage":"একক ছবি","objectDetection":"বস্তু সনাক্তকরণ","disasterAnalysis":"দুর্যোগ বিশ্লেষণ","opticalSar":"অপটিক্যাল + SAR","biTemporal":"দ্বি-সময়ী","advanced":"উন্নত","image":"ছবি","opticalImage":"অপটিক্যাল ছবি","sarImage":"SAR ছবি","beforeImage":"আগের ছবি","afterImage":"পরের ছবি","uploadDesc":"টেনে আনুন এবং ছাড়ুন বা আপলোড করতে ক্লিক করুন","uploadFormats":"GeoTIFF · TIFF · PNG · JPEG · সর্বোচ্চ 2GB","disasterType":"দুর্যোগের ধরন","targetClasses":"লক্ষ্য শ্রেণী","selectAll":"সব নির্বাচন করুন","deselectAll":"সব বাতিল করুন","disasterQuery":"দুর্যোগ প্রশ্ন","optionalQuery":"ঐচ্ছিক প্রশ্ন","askSatquery":"SatQuery কে জিজ্ঞেস করুন","queryPlaceholderDisaster":"যেমন ভূমিধস আক্রান্ত এলাকা সনাক্ত করুন...","queryPlaceholderDetection":"যেমন ভবন ও যানবাহন সনাক্ত করুন...","queryPlaceholderGeneral":"আপনার স্যাটেলাইট ছবি সম্পর্কে প্রশ্ন করুন...","suggestions":"পরামর্শ","analyzeDisaster":"দুর্যোগ বিশ্লেষণ করুন","detectObjects":"বস্তু সনাক্ত করুন","analyzeQuery":"প্রশ্ন বিশ্লেষণ করুন","analyzingDisaster":"দুর্যোগ বিশ্লেষণ হচ্ছে…","detecting":"সনাক্ত হচ্ছে…","analyzing":"বিশ্লেষণ হচ্ছে…","viewer":"স্যাটেলাইট ছবি দর্শক","showOverlays":"ওভারলে দেখান","hideOverlays":"ওভারলে লুকান","lat":"অক্ষাংশ","lon":"দ্রাঘিমাংশ","zoom":"জুম","resolution":"রেজোলিউশন","mode":"মোড","detections":"সনাক্তকরণ","disaster":"দুর্যোগ","severity":"তীব্রতা","affectedArea":"আক্রান্ত এলাকা","agentTrace":"এজেন্ট এক্সিকিউশন ট্রেস","uploadImageFirst":"বিশ্লেষণ শুরু করতে ছবি আপলোড করুন এবং প্রশ্ন লিখুন","selectClassesFirst":"লক্ষ্য শ্রেণী নির্বাচন করুন এবং বস্তু সনাক্ত করুন এ ক্লিক করুন","selectDisasterFirst":"দুর্যোগের ধরন নির্বাচন করুন এবং দুর্যোগ বিশ্লেষণ এ ক্লিক করুন","processingMetadata":"মেটাডেটা প্রক্রিয়া হচ্ছে…"},
        "results": {"title":"বিশ্লেষণ ফলাফল","objectsDetected":"বস্তু","confidence":"আস্থা","loading":"মডিউল লোড হচ্ছে..."},
        "common": {"online":"অনলাইন","offline":"অফলাইন","error":"কিছু ভুল হয়েছে","success":"সফল","warning":"সতর্কতা","search":"ভাষা খুঁজুন..."}
    },
    "ta": {
        "nav": {"overview":"மேலோட்டம்","workspace":"பகுப்பாய்வு பணியிடம்","results":"முடிவுகள்","history":"பகுப்பாய்வு வரலாறு","models":"மாதிரிகள் மற்றும் கருவிகள்","datasets":"தரவுத்தொகுப்புகள்","reports":"அறிக்கைகள்","settings":"அமைப்புகள்","navigation":"வழிசெலுத்தல்","systemStatus":"கணினி நிலை","aiEngine":"AI எஞ்சின்","geoPipeline":"ஜியோ பைப்லைன்","dataLink":"தரவு இணைப்பு","analyst":"பகுப்பாய்வாளர்","systemOnline":"கணினி ஆன்லைன்","syncAgo":"0 நிமிடங்களுக்கு முன் ஒத்திசைவு","utc":"UTC"},
        "workspace": {"title":"பகுப்பாய்வு பணியிடம்","ready":"AI அனுமான எஞ்சின்: தயார்","singleImage":"ஒற்றை படம்","objectDetection":"பொருள் கண்டறிதல்","disasterAnalysis":"பேரழிவு பகுப்பாய்வு","opticalSar":"ஆப்டிக்கல் + SAR","biTemporal":"இரட்டை-காலம்","advanced":"மேம்பட்ட","image":"படம்","opticalImage":"ஆப்டிக்கல் படம்","sarImage":"SAR படம்","beforeImage":"முந்தைய படம்","afterImage":"பிந்தைய படம்","uploadDesc":"இழுத்து விடுங்கள் அல்லது பதிவேற்ற கிளிக் செய்யுங்கள்","uploadFormats":"GeoTIFF · TIFF · PNG · JPEG · அதிகபட்சம் 2GB","disasterType":"பேரழிவு வகை","targetClasses":"இலக்கு வகுப்புகள்","selectAll":"அனைத்தையும் தேர்ந்தெடு","deselectAll":"அனைத்தையும் நீக்கு","disasterQuery":"பேரழிவு வினவல்","optionalQuery":"விருப்பமான வினவல்","askSatquery":"SatQuery ஐ கேளுங்கள்","queryPlaceholderDisaster":"எ.கா. நிலச்சரிவு பாதிக்கப்பட்ட பகுதிகளை கண்டறியுங்கள்...","queryPlaceholderDetection":"எ.கா. கட்டிடங்கள் மற்றும் வாகனங்களை கண்டறியுங்கள்...","queryPlaceholderGeneral":"உங்கள் செயற்கைக்கோள் படத்தைப் பற்றி கேளுங்கள்...","suggestions":"பரிந்துரைகள்","analyzeDisaster":"பேரழிவை பகுப்பாய்வு செய்","detectObjects":"பொருட்களை கண்டறி","analyzeQuery":"வினவலை பகுப்பாய்வு செய்","analyzingDisaster":"பேரழிவு பகுப்பாய்வு நடக்கிறது…","detecting":"கண்டறிதல் நடக்கிறது…","analyzing":"பகுப்பாய்வு நடக்கிறது…","viewer":"செயற்கைக்கோள் படக் காட்சியாளர்","showOverlays":"மேலடுக்குகளை காட்டு","hideOverlays":"மேலடுக்குகளை மறை","lat":"அட்சரேகை","lon":"தீர்க்கரேகை","zoom":"ஜூம்","resolution":"தெளிவுத்திறன்","mode":"பயன்முறை","detections":"கண்டறிதல்","disaster":"பேரழிவு","severity":"தீவிரம்","affectedArea":"பாதிக்கப்பட்ட பகுதி","agentTrace":"முகவர் செயல்படுத்தல் தடம்","uploadImageFirst":"பகுப்பாய்வு தொடங்க படத்தை பதிவேற்றி வினவலை உள்ளிடவும்","selectClassesFirst":"இலக்கு வகுப்புகளை தேர்ந்தெடுத்து பொருட்களை கண்டறி கிளிக் செய்யவும்","selectDisasterFirst":"பேரழிவு வகையை தேர்ந்தெடுத்து பேரழிவை பகுப்பாய்வு செய் கிளிக் செய்யவும்","processingMetadata":"மெட்டாடேட்டா செயலாக்கப்படுகிறது…"},
        "results": {"title":"பகுப்பாய்வு முடிவுகள்","objectsDetected":"பொருட்கள்","confidence":"நம்பகத்தன்மை","loading":"தொகுதி ஏற்றப்படுகிறது..."},
        "common": {"online":"ஆன்லைன்","offline":"ஆஃப்லைன்","error":"ஏதோ தவறு நடந்தது","success":"வெற்றி","warning":"எச்சரிக்கை","search":"மொழி தேடு..."}
    },
    "te": {
        "nav": {"overview":"అవలోకనం","workspace":"విశ్లేషణ కార్యక్షేత్రం","results":"ఫలితాలు","history":"విశ్లేషణ చరిత్ర","models":"మోడల్స్ మరియు సాధనాలు","datasets":"డేటాసెట్‌లు","reports":"నివేదికలు","settings":"సెట్టింగులు","navigation":"నావిగేషన్","systemStatus":"సిస్టమ్ స్థితి","aiEngine":"AI ఇంజిన్","geoPipeline":"జియో పైప్‌లైన్","dataLink":"డేటా లింక్","analyst":"విశ్లేషకుడు","systemOnline":"సిస్టమ్ ఆన్‌లైన్","syncAgo":"0 నిమిషాల క్రితం సింక్","utc":"UTC"},
        "workspace": {"title":"విశ్లేషణ కార్యక్షేత్రం","ready":"AI అనుమాన ఇంజిన్: సిద్ధం","singleImage":"ఒకే చిత్రం","objectDetection":"వస్తువు గుర్తింపు","disasterAnalysis":"విపత్తు విశ్లేషణ","opticalSar":"ఆప్టికల్ + SAR","biTemporal":"ద్వి-కాలిక","advanced":"అధునాతన","image":"చిత్రం","opticalImage":"ఆప్టికల్ చిత్రం","sarImage":"SAR చిత్రం","beforeImage":"ముందు చిత్రం","afterImage":"తర్వాత చిత్రం","uploadDesc":"లాగి వదలండి లేదా అప్‌లోడ్ చేయడానికి క్లిక్ చేయండి","uploadFormats":"GeoTIFF · TIFF · PNG · JPEG · గరిష్టం 2GB","disasterType":"విపత్తు రకం","targetClasses":"లక్ష్య తరగతులు","selectAll":"అన్నీ ఎంచుకోండి","deselectAll":"అన్నీ తీసివేయండి","disasterQuery":"విపత్తు ప్రశ్న","optionalQuery":"ఐచ్ఛిక ప్రశ్న","askSatquery":"SatQuery ని అడగండి","queryPlaceholderDisaster":"ఉదా. భూపాతం ప్రభావిత ప్రాంతాలను గుర్తించండి...","queryPlaceholderDetection":"ఉదా. భవనాలు మరియు వాహనాలను గుర్తించండి...","queryPlaceholderGeneral":"మీ ఉపగ్రహ చిత్రం గురించి ప్రశ్న అడగండి...","suggestions":"సూచనలు","analyzeDisaster":"విపత్తును విశ్లేషించండి","detectObjects":"వస్తువులను గుర్తించండి","analyzeQuery":"ప్రశ్నను విశ్లేషించండి","analyzingDisaster":"విపత్తు విశ్లేషణ జరుగుతోంది…","detecting":"గుర్తింపు జరుగుతోంది…","analyzing":"విశ్లేషణ జరుగుతోంది…","viewer":"ఉపగ్రహ చిత్ర వీక్షకుడు","showOverlays":"పొరలు చూపించు","hideOverlays":"పొరలు దాచు","lat":"అక్షాంశం","lon":"రేఖాంశం","zoom":"జూమ్","resolution":"రిజల్యూషన్","mode":"మోడ్","detections":"గుర్తింపు","disaster":"విపత్తు","severity":"తీవ్రత","affectedArea":"ప్రభావిత ప్రాంతం","agentTrace":"ఏజెంట్ అమలు జాడ","uploadImageFirst":"విశ్లేషణ ప్రారంభించడానికి చిత్రం అప్‌లోడ్ చేసి ప్రశ్న నమోదు చేయండి","selectClassesFirst":"లక్ష్య తరగతులు ఎంచుకుని వస్తువులను గుర్తించండి క్లిక్ చేయండి","selectDisasterFirst":"విపత్తు రకం ఎంచుకుని విపత్తును విశ్లేషించండి క్లిక్ చేయండి","processingMetadata":"మెటాడేటా ప్రాసెస్ అవుతోంది…"},
        "results": {"title":"విశ్లేషణ ఫలితాలు","objectsDetected":"వస్తువులు","confidence":"నమ్మకం","loading":"మాడ్యూల్ లోడ్ అవుతోంది..."},
        "common": {"online":"ఆన్‌లైన్","offline":"ఆఫ్‌లైన్","error":"ఏదో తప్పు జరిగింది","success":"విజయం","warning":"హెచ్చరిక","search":"భాష వెతకండి..."}
    },
    "kn": {
        "nav": {"overview":"ಅವಲೋಕನ","workspace":"ವಿಶ್ಲೇಷಣಾ ಕಾರ್ಯಕ್ಷೇತ್ರ","results":"ಫಲಿತಾಂಶಗಳು","history":"ವಿಶ್ಲೇಷಣಾ ಇತಿಹಾಸ","models":"ಮಾದರಿಗಳು ಮತ್ತು ಉಪಕರಣಗಳು","datasets":"ಡೇಟಾಸೆಟ್‌ಗಳು","reports":"ವರದಿಗಳು","settings":"ಸೆಟ್ಟಿಂಗ್‌ಗಳು","navigation":"ನ್ಯಾವಿಗೇಶನ್","systemStatus":"ಸಿಸ್ಟಮ್ ಸ್ಥಿತಿ","aiEngine":"AI ಎಂಜಿನ್","geoPipeline":"ಜಿಯೊ ಪೈಪ್‌ಲೈನ್","dataLink":"ಡೇಟಾ ಲಿಂಕ್","analyst":"ವಿಶ್ಲೇಷಕ","systemOnline":"ಸಿಸ್ಟಮ್ ಆನ್‌ಲೈನ್","syncAgo":"0 ನಿಮಿಷಗಳ ಹಿಂದೆ ಸಿಂಕ್","utc":"UTC"},
        "workspace": {"title":"ವಿಶ್ಲೇಷಣಾ ಕಾರ್ಯಕ್ಷೇತ್ರ","ready":"AI ಅನುಮಾನ ಎಂಜಿನ್: ಸಿದ್ಧ","singleImage":"ಒಂದೇ ಚಿತ್ರ","objectDetection":"ವಸ್ತು ಪತ್ತೆ","disasterAnalysis":"ವಿಪತ್ತು ವಿಶ್ಲೇಷಣೆ","opticalSar":"ಆಪ್ಟಿಕಲ್ + SAR","biTemporal":"ಬಿ-ಟೆಂಪೊರಲ್","advanced":"ಮುಂದುವರಿದ","image":"ಚಿತ್ರ","opticalImage":"ಆಪ್ಟಿಕಲ್ ಚಿತ್ರ","sarImage":"SAR ಚಿತ್ರ","beforeImage":"ಮೊದಲಿನ ಚಿತ್ರ","afterImage":"ನಂತರದ ಚಿತ್ರ","uploadDesc":"ಎಳೆದು ಬಿಡಿ ಅಥವಾ ಅಪ್‌ಲೋಡ್ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ","uploadFormats":"GeoTIFF · TIFF · PNG · JPEG · ಗರಿಷ್ಠ 2GB","disasterType":"ವಿಪತ್ತು ಪ್ರಕಾರ","targetClasses":"ಗುರಿ ವರ್ಗಗಳು","selectAll":"ಎಲ್ಲಾ ಆಯ್ಕೆ","deselectAll":"ಎಲ್ಲಾ ತೆಗೆ","disasterQuery":"ವಿಪತ್ತು ಪ್ರಶ್ನೆ","optionalQuery":"ಐಚ್ಛಿಕ ಪ್ರಶ್ನೆ","askSatquery":"SatQuery ಕೇಳಿ","queryPlaceholderDisaster":"ಉದಾ. ಭೂಕುಸಿತ ಪ್ರಭಾವಿತ ಪ್ರದೇಶಗಳನ್ನು ಪತ್ತೆ ಹಚ್ಚಿ...","queryPlaceholderDetection":"ಉದಾ. ಕಟ್ಟಡಗಳು ಮತ್ತು ವಾಹನಗಳನ್ನು ಪತ್ತೆ ಹಚ್ಚಿ...","queryPlaceholderGeneral":"ನಿಮ್ಮ ಉಪಗ್ರಹ ಚಿತ್ರದ ಬಗ್ಗೆ ಪ್ರಶ್ನೆ ಕೇಳಿ...","suggestions":"ಸಲಹೆಗಳು","analyzeDisaster":"ವಿಪತ್ತು ವಿಶ್ಲೇಷಿಸಿ","detectObjects":"ವಸ್ತುಗಳನ್ನು ಪತ್ತೆ ಮಾಡಿ","analyzeQuery":"ಪ್ರಶ್ನೆ ವಿಶ್ಲೇಷಿಸಿ","analyzingDisaster":"ವಿಪತ್ತು ವಿಶ್ಲೇಷಣೆ ನಡೆಯುತ್ತಿದೆ…","detecting":"ಪತ್ತೆ ನಡೆಯುತ್ತಿದೆ…","analyzing":"ವಿಶ್ಲೇಷಣೆ ನಡೆಯುತ್ತಿದೆ…","viewer":"ಉಪಗ್ರಹ ಚಿತ್ರ ವೀಕ್ಷಕ","showOverlays":"ಓವರ್‌ಲೇ ತೋರಿಸು","hideOverlays":"ಓವರ್‌ಲೇ ಮರೆಮಾಚು","lat":"ಅಕ್ಷಾಂಶ","lon":"ರೇಖಾಂಶ","zoom":"ಜೂಮ್","resolution":"ರೆಸಲ್ಯೂಶನ್","mode":"ಮೋಡ್","detections":"ಪತ್ತೆ","disaster":"ವಿಪತ್ತು","severity":"ತೀವ್ರತೆ","affectedArea":"ಪ್ರಭಾವಿತ ಪ್ರದೇಶ","agentTrace":"ಏಜೆಂಟ್ ಎಕ್ಸಿಕ್ಯೂಶನ್ ಟ್ರೇಸ್","uploadImageFirst":"ವಿಶ್ಲೇಷಣೆ ಪ್ರಾರಂಭಿಸಲು ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಮತ್ತು ಪ್ರಶ್ನೆ ನಮೂದಿಸಿ","selectClassesFirst":"ಗುರಿ ವರ್ಗಗಳನ್ನು ಆಯ್ಕೆ ಮಾಡಿ ಮತ್ತು ವಸ್ತುಗಳನ್ನು ಪತ್ತೆ ಮಾಡಿ ಕ್ಲಿಕ್ ಮಾಡಿ","selectDisasterFirst":"ವಿಪತ್ತು ಪ್ರಕಾರ ಆಯ್ಕೆ ಮಾಡಿ ಮತ್ತು ವಿಪತ್ತು ವಿಶ್ಲೇಷಿಸಿ ಕ್ಲಿಕ್ ಮಾಡಿ","processingMetadata":"ಮೆಟಾಡೇಟಾ ಪ್ರಕ್ರಿಯೆ ನಡೆಯುತ್ತಿದೆ…"},
        "results": {"title":"ವಿಶ್ಲೇಷಣಾ ಫಲಿತಾಂಶಗಳು","objectsDetected":"ವಸ್ತುಗಳು","confidence":"ವಿಶ್ವಾಸ","loading":"ಮಾಡ್ಯೂಲ್ ಲೋಡ್ ಆಗುತ್ತಿದೆ..."},
        "common": {"online":"ಆನ್‌ಲೈನ್","offline":"ಆಫ್‌ಲೈನ್","error":"ಏನೋ ತಪ್ಪಾಯಿತು","success":"ಯಶಸ್ಸು","warning":"ಎಚ್ಚರಿಕೆ","search":"ಭಾಷೆ ಹುಡುಕಿ..."}
    },
    "ml": {
        "nav": {"overview":"അവലോകനം","workspace":"വിശകലന ജോലിസ്ഥലം","results":"ഫലങ്ങൾ","history":"വിശകലന ചരിത്രം","models":"മോഡലുകളും ഉപകരണങ്ങളും","datasets":"ഡേറ്റാസെറ്റുകൾ","reports":"റിപ്പോർട്ടുകൾ","settings":"ക്രമീകരണങ്ങൾ","navigation":"നാവിഗേഷൻ","systemStatus":"സിസ്റ്റം സ്ഥിതി","aiEngine":"AI എഞ്ചിൻ","geoPipeline":"ജിയോ പൈപ്പ്‌ലൈൻ","dataLink":"ഡേറ്റ ലിങ്ക്","analyst":"വിശകലകൻ","systemOnline":"സിസ്റ്റം ഓൺലൈൻ","syncAgo":"0 മിനിറ്റ് മുമ്പ് സമന്വയം","utc":"UTC"},
        "workspace": {"title":"വിശകലന ജോലിസ്ഥലം","ready":"AI അനുമാന എഞ്ചിൻ: തയ്യാർ","singleImage":"ഒറ്റ ചിത്രം","objectDetection":"വസ്തു കണ്ടെത്തൽ","disasterAnalysis":"ദുരന്ത വിശകലനം","opticalSar":"ഒപ്റ്റിക്കൽ + SAR","biTemporal":"ദ്വി-കാലം","advanced":"വിപുലീകൃത","image":"ചിത്രം","opticalImage":"ഒപ്റ്റിക്കൽ ചിത്രം","sarImage":"SAR ചിത്രം","beforeImage":"മുമ്പത്തെ ചിത്രം","afterImage":"ശേഷമുള്ള ചിത്രം","uploadDesc":"വലിച്ചിടുക അല്ലെങ്കിൽ അപ്‌ലോഡ് ചെയ്യാൻ ക്ലിക്ക് ചെയ്യുക","uploadFormats":"GeoTIFF · TIFF · PNG · JPEG · പരമാവധി 2GB","disasterType":"ദുരന്ത തരം","targetClasses":"ലക്ഷ്യ ക്ലാസുകൾ","selectAll":"എല്ലാം തിരഞ്ഞെടുക്കുക","deselectAll":"എല്ലാം നീക്കുക","disasterQuery":"ദുരന്ത ചോദ്യം","optionalQuery":"ഐച്ഛിക ചോദ്യം","askSatquery":"SatQuery യോട് ചോദിക്കുക","queryPlaceholderDisaster":"ഉദാ. ഉരുൾപൊട്ടൽ ബാധിത പ്രദേശങ്ങൾ കണ്ടെത്തുക...","queryPlaceholderDetection":"ഉദാ. കെട്ടിടങ്ങളും വാഹനങ്ങളും കണ്ടെത്തുക...","queryPlaceholderGeneral":"നിങ്ങളുടെ ഉപഗ്രഹ ചിത്രത്തെക്കുറിച്ച് ചോദ്യം ചോദിക്കുക...","suggestions":"നിർദ്ദേശങ്ങൾ","analyzeDisaster":"ദുരന്തം വിശകലനം ചെയ്യുക","detectObjects":"വസ്തുക്കൾ കണ്ടെത്തുക","analyzeQuery":"ചോദ്യം വിശകലനം ചെയ്യുക","analyzingDisaster":"ദുരന്ത വിശകലനം നടക്കുന്നു…","detecting":"കണ്ടെത്തൽ നടക്കുന്നു…","analyzing":"വിശകലനം നടക്കുന്നു…","viewer":"ഉപഗ്രഹ ചിത്ര കാഴ്ചക്കാരൻ","showOverlays":"ഓവർലേകൾ കാണിക്കുക","hideOverlays":"ഓവർലേകൾ മറയ്ക്കുക","lat":"അക്ഷാംശം","lon":"രേഖാംശം","zoom":"സൂം","resolution":"റെസലൂഷൻ","mode":"മോഡ്","detections":"കണ്ടെത്തൽ","disaster":"ദുരന്തം","severity":"തീവ്രത","affectedArea":"ബാധിത പ്രദേശം","agentTrace":"ഏജൻ്റ് എക്സിക്യൂഷൻ ട്രെയ്സ്","uploadImageFirst":"വിശകലനം ആരംഭിക്കാൻ ചിത്രം അപ്‌ലോഡ് ചെയ്ത് ചോദ്യം നൽകുക","selectClassesFirst":"ലക്ഷ്യ ക്ലാസുകൾ തിരഞ്ഞെടുത്ത് വസ്തുക്കൾ കണ്ടെത്തുക ക്ലിക്ക് ചെയ്യുക","selectDisasterFirst":"ദുരന്ത തരം തിരഞ്ഞെടുത്ത് ദുരന്തം വിശകലനം ചെയ്യുക ക്ലിക്ക് ചെയ്യുക","processingMetadata":"മെറ്റാഡേറ്റ പ്രോസസ്സ് ചെയ്യുന്നു…"},
        "results": {"title":"വിശകലന ഫലങ്ങൾ","objectsDetected":"വസ്തുക്കൾ","confidence":"ആത്മവിശ്വാസം","loading":"മൊഡ്യൂൾ ലോഡ് ചെയ്യുന്നു..."},
        "common": {"online":"ഓൺലൈൻ","offline":"ഓഫ്‌ലൈൻ","error":"എന്തോ തകരാർ സംഭവിച്ചു","success":"വിജയം","warning":"മുന്നറിയിപ്പ്","search":"ഭാഷ തിരയുക..."}
    },
    "gu": {
        "nav": {"overview":"ઝાંખી","workspace":"વિશ્લેષણ કાર્યક્ષેત્ર","results":"પરિણામો","history":"વિશ્લેષણ ઇતિહાસ","models":"મોડેલ અને સાધનો","datasets":"ડેટાસેટ","reports":"અહેવાલો","settings":"સેટિંગ્સ","navigation":"નેવિગેશન","systemStatus":"સિસ્ટમ સ્થિતિ","aiEngine":"AI એન્જિન","geoPipeline":"જિઓ પાઇપલાઇન","dataLink":"ડેટા લિંક","analyst":"વિશ્લેષક","systemOnline":"સિસ્ટમ ઓનલાઇન","syncAgo":"0 મિનિટ પહેલા સિંક","utc":"UTC"},
        "workspace": {"title":"વિશ્લેષણ કાર્યક્ષેત્ર","ready":"AI અનુમાન એન્જિન: તૈયાર","singleImage":"એકલ છબી","objectDetection":"વસ્તુ શોધ","disasterAnalysis":"આફત વિશ્લેષણ","opticalSar":"ઓપ્ટિકલ + SAR","biTemporal":"દ્વિ-કાળ","advanced":"અદ્યતન","image":"છબી","opticalImage":"ઓપ્ટિકલ છબી","sarImage":"SAR છબી","beforeImage":"પૂર્વ છબી","afterImage":"બાદ છબી","uploadDesc":"ખેંચો અને છોડો અથવા અપલોડ કરવા ક્લિક કરો","uploadFormats":"GeoTIFF · TIFF · PNG · JPEG · મહત્તમ 2GB","disasterType":"આફત પ્રકાર","targetClasses":"લક્ષ્ય વર્ગ","selectAll":"બધા પસંદ કરો","deselectAll":"બધા હટાવો","disasterQuery":"આફત પ્રશ્ન","optionalQuery":"વૈકલ્પિક પ્રશ્ન","askSatquery":"SatQuery ને પૂછો","queryPlaceholderDisaster":"દા.ત. ભૂસ્ખલન પ્રભાવિત વિસ્તારો શોધો...","queryPlaceholderDetection":"દા.ત. ઇમારતો અને વાહનો શોધો...","queryPlaceholderGeneral":"તમારી ઉપગ્રહ છબી વિશે પ્રશ્ન પૂછો...","suggestions":"સૂચનો","analyzeDisaster":"આફત વિશ્લેષણ કરો","detectObjects":"વસ્તુઓ શોધો","analyzeQuery":"પ્રશ્ન વિશ્લેષણ કરો","analyzingDisaster":"આફત વિશ્લેષણ ચાલી રહ્યું છે…","detecting":"શોધ ચાલી રહી છે…","analyzing":"વિશ્લેષણ ચાલી રહ્યું છે…","viewer":"ઉપગ્રહ છબી દર્શક","showOverlays":"ઓવરલે બતાવો","hideOverlays":"ઓવરલે છુપાવો","lat":"અક્ષાંશ","lon":"રેખાંશ","zoom":"ઝૂમ","resolution":"રિઝોલ્યુશન","mode":"મોડ","detections":"શોધ","disaster":"આફત","severity":"ગંભીરતા","affectedArea":"અસરગ્રસ્ત વિસ્તાર","agentTrace":"એજન્ટ એક્ઝિક્યૂશન ટ્રેસ","uploadImageFirst":"વિશ્લેષણ શરૂ કરવા છબી અપલોડ કરો અને પ્રશ્ન દાખલ કરો","selectClassesFirst":"લક્ષ્ય વર્ગ પસંદ કરો અને વસ્તુઓ શોધો ક્લિક કરો","selectDisasterFirst":"આફત પ્રકાર પસંદ કરો અને આફત વિશ્લેષણ ક્લિક કરો","processingMetadata":"મેટાડેટા પ્રક્રિયા ચાલી રહી છે…"},
        "results": {"title":"વિશ્લેષણ પરિણામો","objectsDetected":"વસ્તુઓ","confidence":"વિશ્વાસ","loading":"મોડ્યુલ લોડ થઈ રહ્યો છે..."},
        "common": {"online":"ઓનલાઇન","offline":"ઑફ્લાઇન","error":"કંઈક ખોટું ગયું","success":"સફળ","warning":"ચેતવણી","search":"ભાષા શોધો..."}
    },
    "pa": {
        "nav": {"overview":"ਸੰਖੇਪ","workspace":"ਵਿਸ਼ਲੇਸ਼ਣ ਕਾਰਜਸਥਾਨ","results":"ਨਤੀਜੇ","history":"ਵਿਸ਼ਲੇਸ਼ਣ ਇਤਿਹਾਸ","models":"ਮਾਡਲ ਅਤੇ ਔਜ਼ਾਰ","datasets":"ਡੇਟਾਸੈੱਟ","reports":"ਰਿਪੋਰਟਾਂ","settings":"ਸੈਟਿੰਗਾਂ","navigation":"ਨੇਵੀਗੇਸ਼ਨ","systemStatus":"ਸਿਸਟਮ ਸਥਿਤੀ","aiEngine":"AI ਇੰਜਣ","geoPipeline":"ਜਿਓ ਪਾਈਪਲਾਈਨ","dataLink":"ਡੇਟਾ ਲਿੰਕ","analyst":"ਵਿਸ਼ਲੇਸ਼ਕ","systemOnline":"ਸਿਸਟਮ ਔਨਲਾਈਨ","syncAgo":"0 ਮਿੰਟ ਪਹਿਲਾਂ ਸਿੰਕ","utc":"UTC"},
        "workspace": {"title":"ਵਿਸ਼ਲੇਸ਼ਣ ਕਾਰਜਸਥਾਨ","ready":"AI ਅਨੁਮਾਨ ਇੰਜਣ: ਤਿਆਰ","singleImage":"ਇਕੱਲੀ ਤਸਵੀਰ","objectDetection":"ਵਸਤੂ ਖੋਜ","disasterAnalysis":"ਆਫ਼ਤ ਵਿਸ਼ਲੇਸ਼ਣ","opticalSar":"ਆਪਟੀਕਲ + SAR","biTemporal":"ਦੋਹਰੀ-ਸਮੇਂ","advanced":"ਉੱਨਤ","image":"ਤਸਵੀਰ","opticalImage":"ਆਪਟੀਕਲ ਤਸਵੀਰ","sarImage":"SAR ਤਸਵੀਰ","beforeImage":"ਪਹਿਲਾਂ ਦੀ ਤਸਵੀਰ","afterImage":"ਬਾਅਦ ਦੀ ਤਸਵੀਰ","uploadDesc":"ਖਿੱਚੋ ਅਤੇ ਛੱਡੋ ਜਾਂ ਅੱਪਲੋਡ ਕਰਨ ਲਈ ਕਲਿੱਕ ਕਰੋ","uploadFormats":"GeoTIFF · TIFF · PNG · JPEG · ਵੱਧ ਤੋਂ ਵੱਧ 2GB","disasterType":"ਆਫ਼ਤ ਕਿਸਮ","targetClasses":"ਟੀਚਾ ਵਰਗ","selectAll":"ਸਭ ਚੁਣੋ","deselectAll":"ਸਭ ਹਟਾਓ","disasterQuery":"ਆਫ਼ਤ ਸਵਾਲ","optionalQuery":"ਵਿਕਲਪਿਕ ਸਵਾਲ","askSatquery":"SatQuery ਨੂੰ ਪੁੱਛੋ","queryPlaceholderDisaster":"ਜਿਵੇਂ ਭੂਸਖਲਣ ਪ੍ਰਭਾਵਿਤ ਖੇਤਰਾਂ ਦਾ ਪਤਾ ਲਗਾਓ...","queryPlaceholderDetection":"ਜਿਵੇਂ ਇਮਾਰਤਾਂ ਅਤੇ ਵਾਹਨਾਂ ਦਾ ਪਤਾ ਲਗਾਓ...","queryPlaceholderGeneral":"ਆਪਣੀ ਸੈਟੇਲਾਈਟ ਤਸਵੀਰ ਬਾਰੇ ਸਵਾਲ ਪੁੱਛੋ...","suggestions":"ਸੁਝਾਅ","analyzeDisaster":"ਆਫ਼ਤ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ","detectObjects":"ਵਸਤੂਆਂ ਦਾ ਪਤਾ ਲਗਾਓ","analyzeQuery":"ਸਵਾਲ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ","analyzingDisaster":"ਆਫ਼ਤ ਵਿਸ਼ਲੇਸ਼ਣ ਚੱਲ ਰਿਹਾ ਹੈ…","detecting":"ਖੋਜ ਚੱਲ ਰਹੀ ਹੈ…","analyzing":"ਵਿਸ਼ਲੇਸ਼ਣ ਚੱਲ ਰਿਹਾ ਹੈ…","viewer":"ਸੈਟੇਲਾਈਟ ਤਸਵੀਰ ਦਰਸ਼ਕ","showOverlays":"ਓਵਰਲੇ ਦਿਖਾਓ","hideOverlays":"ਓਵਰਲੇ ਲੁਕਾਓ","lat":"ਅਕਸ਼ਾਂਸ਼","lon":"ਦੇਸ਼ਾਂਤਰ","zoom":"ਜ਼ੂਮ","resolution":"ਰੈਜ਼ੋਲਿਊਸ਼ਨ","mode":"ਮੋਡ","detections":"ਖੋਜ","disaster":"ਆਫ਼ਤ","severity":"ਗੰਭੀਰਤਾ","affectedArea":"ਪ੍ਰਭਾਵਿਤ ਖੇਤਰ","agentTrace":"ਏਜੰਟ ਐਗਜ਼ੀਕਿਊਸ਼ਨ ਟ੍ਰੇਸ","uploadImageFirst":"ਵਿਸ਼ਲੇਸ਼ਣ ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਤਸਵੀਰ ਅੱਪਲੋਡ ਕਰੋ ਅਤੇ ਸਵਾਲ ਦਰਜ ਕਰੋ","selectClassesFirst":"ਟੀਚਾ ਵਰਗ ਚੁਣੋ ਅਤੇ ਵਸਤੂਆਂ ਦਾ ਪਤਾ ਲਗਾਓ ਤੇ ਕਲਿੱਕ ਕਰੋ","selectDisasterFirst":"ਆਫ਼ਤ ਕਿਸਮ ਚੁਣੋ ਅਤੇ ਆਫ਼ਤ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ ਤੇ ਕਲਿੱਕ ਕਰੋ","processingMetadata":"ਮੈਟਾਡੇਟਾ ਪ੍ਰੋਸੈਸ ਹੋ ਰਿਹਾ ਹੈ…"},
        "results": {"title":"ਵਿਸ਼ਲੇਸ਼ਣ ਨਤੀਜੇ","objectsDetected":"ਵਸਤੂਆਂ","confidence":"ਭਰੋਸਾ","loading":"ਮੋਡਿਊਲ ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ..."},
        "common": {"online":"ਔਨਲਾਈਨ","offline":"ਔਫਲਾਈਨ","error":"ਕੁਝ ਗਲਤ ਹੋਇਆ","success":"ਸਫਲ","warning":"ਚੇਤਾਵਨੀ","search":"ਭਾਸ਼ਾ ਖੋਜੋ..."}
    },
    "ur": {
        "nav": {"overview":"جائزہ","workspace":"تجزیاتی کام کی جگہ","results":"نتائج","history":"تجزیہ تاریخ","models":"ماڈل اور ٹولز","datasets":"ڈیٹاسیٹ","reports":"رپورٹیں","settings":"ترتیبات","navigation":"نیویگیشن","systemStatus":"سسٹم کی حیثیت","aiEngine":"AI انجن","geoPipeline":"جیو پائپ لائن","dataLink":"ڈیٹا لنک","analyst":"تجزیہ کار","systemOnline":"سسٹم آن لائن","syncAgo":"0 منٹ پہلے سنک","utc":"UTC"},
        "workspace": {"title":"تجزیاتی کام کی جگہ","ready":"AI انفرنس انجن: تیار","singleImage":"واحد تصویر","objectDetection":"اشیاء کا پتہ لگانا","disasterAnalysis":"آفت تجزیہ","opticalSar":"آپٹیکل + SAR","biTemporal":"دو وقتی","advanced":"جدید","image":"تصویر","opticalImage":"آپٹیکل تصویر","sarImage":"SAR تصویر","beforeImage":"پہلے کی تصویر","afterImage":"بعد کی تصویر","uploadDesc":"گھسیٹیں اور چھوڑیں یا اپ لوڈ کریں","uploadFormats":"GeoTIFF · TIFF · PNG · JPEG · زیادہ سے زیادہ 2GB","disasterType":"آفت کی قسم","targetClasses":"ہدف کلاسز","selectAll":"سب منتخب کریں","deselectAll":"سب ہٹائیں","disasterQuery":"آفت سوال","optionalQuery":"اختیاری سوال","askSatquery":"SatQuery سے پوچھیں","queryPlaceholderDisaster":"مثلاً لینڈ سلائیڈ متاثرہ علاقوں کا پتہ لگائیں...","queryPlaceholderDetection":"مثلاً عمارتیں اور گاڑیاں تلاش کریں...","queryPlaceholderGeneral":"اپنی سیٹلائٹ تصویر کے بارے میں سوال کریں...","suggestions":"تجاویز","analyzeDisaster":"آفت کا تجزیہ کریں","detectObjects":"اشیاء تلاش کریں","analyzeQuery":"سوال کا تجزیہ کریں","analyzingDisaster":"آفت کا تجزیہ ہو رہا ہے…","detecting":"پتہ لگ رہا ہے…","analyzing":"تجزیہ ہو رہا ہے…","viewer":"سیٹلائٹ تصویر ناظر","showOverlays":"اوورلے دکھائیں","hideOverlays":"اوورلے چھپائیں","lat":"عرض البلد","lon":"طول البلد","zoom":"زوم","resolution":"ریزولوشن","mode":"موڈ","detections":"پتہ لگانا","disaster":"آفت","severity":"شدت","affectedArea":"متاثرہ علاقہ","agentTrace":"ایجنٹ ایگزیکیوشن ٹریس","uploadImageFirst":"تجزیہ شروع کرنے کے لیے تصویر اپ لوڈ کریں اور سوال درج کریں","selectClassesFirst":"ہدف کلاسز منتخب کریں اور اشیاء تلاش کریں پر کلک کریں","selectDisasterFirst":"آفت کی قسم منتخب کریں اور آفت کا تجزیہ پر کلک کریں","processingMetadata":"میٹا ڈیٹا پراسیس ہو رہا ہے…"},
        "results": {"title":"تجزیہ نتائج","objectsDetected":"اشیاء","confidence":"اعتماد","loading":"ماڈیول لوڈ ہو رہا ہے..."},
        "common": {"online":"آن لائن","offline":"آف لائن","error":"کچھ غلط ہوا","success":"کامیاب","warning":"انتباہ","search":"زبان تلاش کریں..."}
    },
    "es": {
        "nav": {"overview":"Resumen","workspace":"Espacio de trabajo","results":"Resultados","history":"Historial de análisis","models":"Modelos y herramientas","datasets":"Conjuntos de datos","reports":"Informes","settings":"Configuración","navigation":"NAVEGACIÓN","systemStatus":"ESTADO DEL SISTEMA","aiEngine":"Motor AI","geoPipeline":"Tubería geoespacial","dataLink":"Enlace de datos","analyst":"Analista","systemOnline":"SISTEMA EN LÍNEA","syncAgo":"SINCRONIZADO HACE 0m","utc":"UTC"},
        "workspace": {"title":"Espacio de trabajo de análisis","ready":"MOTOR DE INFERENCIA AI: LISTO","singleImage":"Imagen única","objectDetection":"Detección de objetos","disasterAnalysis":"Análisis de desastres","opticalSar":"Óptico + SAR","biTemporal":"Bi-temporal","advanced":"Avanzado","image":"IMAGEN","opticalImage":"IMAGEN ÓPTICA","sarImage":"IMAGEN SAR","beforeImage":"IMAGEN ANTES","afterImage":"IMAGEN DESPUÉS","uploadDesc":"Arrastra y suelta o haz clic para subir","uploadFormats":"GeoTIFF · TIFF · PNG · JPEG · Máx 2GB","disasterType":"TIPO DE DESASTRE","targetClasses":"CLASES OBJETIVO","selectAll":"Seleccionar todo","deselectAll":"Deseleccionar todo","disasterQuery":"CONSULTA DE DESASTRE","optionalQuery":"CONSULTA OPCIONAL","askSatquery":"PREGUNTAR A SATQUERY","queryPlaceholderDisaster":"ej. Detectar áreas afectadas por deslizamientos...","queryPlaceholderDetection":"ej. Detectar edificios y vehículos...","queryPlaceholderGeneral":"Haz una pregunta sobre tu imagen satelital...","suggestions":"SUGERENCIAS","analyzeDisaster":"Analizar desastre","detectObjects":"Detectar objetos","analyzeQuery":"Analizar consulta","analyzingDisaster":"Analizando desastre…","detecting":"Detectando…","analyzing":"Analizando…","viewer":"VISOR DE IMAGEN SATELITAL","showOverlays":"Mostrar capas","hideOverlays":"Ocultar capas","lat":"LAT","lon":"LON","zoom":"ZOOM","resolution":"RESOLUCIÓN","mode":"MODO","detections":"DETECCIONES","disaster":"DESASTRE","severity":"SEVERIDAD","affectedArea":"ÁREA AFECTADA","agentTrace":"TRAZA DE EJECUCIÓN DEL AGENTE","uploadImageFirst":"Sube imágenes e ingresa una consulta para comenzar el análisis","selectClassesFirst":"Selecciona clases objetivo y haz clic en Detectar objetos","selectDisasterFirst":"Selecciona el tipo de desastre y haz clic en Analizar desastre","processingMetadata":"Procesando metadatos…"},
        "results": {"title":"Resultados del análisis","objectsDetected":"objetos","confidence":"Confianza","loading":"Cargando módulo..."},
        "common": {"online":"en línea","offline":"fuera de línea","error":"Algo salió mal","success":"Éxito","warning":"Advertencia","search":"Buscar idioma..."}
    },
    "fr": {
        "nav": {"overview":"Aperçu","workspace":"Espace de travail","results":"Résultats","history":"Historique d'analyse","models":"Modèles et outils","datasets":"Ensembles de données","reports":"Rapports","settings":"Paramètres","navigation":"NAVIGATION","systemStatus":"ÉTAT DU SYSTÈME","aiEngine":"Moteur IA","geoPipeline":"Pipeline géospatial","dataLink":"Lien de données","analyst":"Analyste","systemOnline":"SYSTÈME EN LIGNE","syncAgo":"SYNCHRONISÉ IL Y A 0m","utc":"UTC"},
        "workspace": {"title":"Espace de travail d'analyse","ready":"MOTEUR D'INFÉRENCE IA : PRÊT","singleImage":"Image unique","objectDetection":"Détection d'objets","disasterAnalysis":"Analyse de catastrophes","opticalSar":"Optique + SAR","biTemporal":"Bi-temporel","advanced":"Avancé","image":"IMAGE","opticalImage":"IMAGE OPTIQUE","sarImage":"IMAGE SAR","beforeImage":"IMAGE AVANT","afterImage":"IMAGE APRÈS","uploadDesc":"Glissez-déposez ou cliquez pour télécharger","uploadFormats":"GeoTIFF · TIFF · PNG · JPEG · Max 2Go","disasterType":"TYPE DE CATASTROPHE","targetClasses":"CLASSES CIBLES","selectAll":"Tout sélectionner","deselectAll":"Tout désélectionner","disasterQuery":"REQUÊTE DE CATASTROPHE","optionalQuery":"REQUÊTE OPTIONNELLE","askSatquery":"DEMANDER À SATQUERY","queryPlaceholderDisaster":"ex. Détecter les zones affectées par des glissements...","queryPlaceholderDetection":"ex. Détecter les bâtiments et les véhicules...","queryPlaceholderGeneral":"Posez une question sur votre image satellite...","suggestions":"SUGGESTIONS","analyzeDisaster":"Analyser la catastrophe","detectObjects":"Détecter les objets","analyzeQuery":"Analyser la requête","analyzingDisaster":"Analyse de catastrophe en cours…","detecting":"Détection en cours…","analyzing":"Analyse en cours…","viewer":"VISIONNEUR D'IMAGE SATELLITE","showOverlays":"Afficher les couches","hideOverlays":"Masquer les couches","lat":"LAT","lon":"LON","zoom":"ZOOM","resolution":"RÉSOLUTION","mode":"MODE","detections":"DÉTECTIONS","disaster":"CATASTROPHE","severity":"SÉVÉRITÉ","affectedArea":"ZONE AFFECTÉE","agentTrace":"TRACE D'EXÉCUTION DE L'AGENT","uploadImageFirst":"Téléchargez des images et saisissez une requête pour commencer l'analyse","selectClassesFirst":"Sélectionnez les classes cibles et cliquez sur Détecter les objets","selectDisasterFirst":"Sélectionnez le type de catastrophe et cliquez sur Analyser la catastrophe","processingMetadata":"Traitement des métadonnées…"},
        "results": {"title":"Résultats d'analyse","objectsDetected":"objets","confidence":"Confiance","loading":"Chargement du module..."},
        "common": {"online":"en ligne","offline":"hors ligne","error":"Quelque chose s'est mal passé","success":"Succès","warning":"Avertissement","search":"Rechercher une langue..."}
    },
    "de": {
        "nav": {"overview":"Übersicht","workspace":"Analysearbeitsbereich","results":"Ergebnisse","history":"Analysehistorie","models":"Modelle & Werkzeuge","datasets":"Datensätze","reports":"Berichte","settings":"Einstellungen","navigation":"NAVIGATION","systemStatus":"SYSTEMSTATUS","aiEngine":"KI-Motor","geoPipeline":"Geo-Pipeline","dataLink":"Datenverbindung","analyst":"Analyst","systemOnline":"SYSTEM ONLINE","syncAgo":"VOR 0m SYNCHRONISIERT","utc":"UTC"},
        "workspace": {"title":"Analysearbeitsbereich","ready":"KI-INFERENZMOTOR: BEREIT","singleImage":"Einzelbild","objectDetection":"Objekterkennung","disasterAnalysis":"Katastrophenanalyse","opticalSar":"Optisch + SAR","biTemporal":"Bi-temporal","advanced":"Erweitert","image":"BILD","opticalImage":"OPTISCHES BILD","sarImage":"SAR-BILD","beforeImage":"VORHER-BILD","afterImage":"NACHHER-BILD","uploadDesc":"Ziehen und ablegen oder zum Hochladen klicken","uploadFormats":"GeoTIFF · TIFF · PNG · JPEG · Max 2GB","disasterType":"KATASTROPHENTYP","targetClasses":"ZIELKLASSEN","selectAll":"Alle auswählen","deselectAll":"Alle abwählen","disasterQuery":"KATASTROPHENANFRAGE","optionalQuery":"OPTIONALE ANFRAGE","askSatquery":"SATQUERY FRAGEN","queryPlaceholderDisaster":"z.B. Erdrutschbetroffene Gebiete erkennen...","queryPlaceholderDetection":"z.B. Gebäude und Fahrzeuge erkennen...","queryPlaceholderGeneral":"Stellen Sie eine Frage zu Ihrem Satellitenbild...","suggestions":"VORSCHLÄGE","analyzeDisaster":"Katastrophe analysieren","detectObjects":"Objekte erkennen","analyzeQuery":"Anfrage analysieren","analyzingDisaster":"Katastrophenanalyse läuft…","detecting":"Erkennung läuft…","analyzing":"Analyse läuft…","viewer":"SATELLITENBILD-BETRACHTER","showOverlays":"Überlagerungen anzeigen","hideOverlays":"Überlagerungen ausblenden","lat":"BREITE","lon":"LÄNGE","zoom":"ZOOM","resolution":"AUFLÖSUNG","mode":"MODUS","detections":"ERKENNUNGEN","disaster":"KATASTROPHE","severity":"SCHWERE","affectedArea":"BETROFFENES GEBIET","agentTrace":"AGENT-AUSFÜHRUNGSPROTOKOLL","uploadImageFirst":"Laden Sie Bilder hoch und geben Sie eine Anfrage ein, um die Analyse zu starten","selectClassesFirst":"Wählen Sie Zielklassen aus und klicken Sie auf Objekte erkennen","selectDisasterFirst":"Wählen Sie den Katastrophentyp aus und klicken Sie auf Katastrophe analysieren","processingMetadata":"Metadaten werden verarbeitet…"},
        "results": {"title":"Analyseergebnisse","objectsDetected":"Objekte","confidence":"Konfidenz","loading":"Modul wird geladen..."},
        "common": {"online":"online","offline":"offline","error":"Etwas ist schiefgelaufen","success":"Erfolg","warning":"Warnung","search":"Sprache suchen..."}
    },
    "pt": {
        "nav": {"overview":"Visão geral","workspace":"Espaço de trabalho","results":"Resultados","history":"Histórico de análise","models":"Modelos e ferramentas","datasets":"Conjuntos de dados","reports":"Relatórios","settings":"Configurações","navigation":"NAVEGAÇÃO","systemStatus":"STATUS DO SISTEMA","aiEngine":"Motor de IA","geoPipeline":"Pipeline geoespacial","dataLink":"Link de dados","analyst":"Analista","systemOnline":"SISTEMA ON-LINE","syncAgo":"SINCRONIZADO HÁ 0m","utc":"UTC"},
        "workspace": {"title":"Espaço de trabalho de análise","ready":"MOTOR DE INFERÊNCIA IA: PRONTO","singleImage":"Imagem única","objectDetection":"Detecção de objetos","disasterAnalysis":"Análise de desastres","opticalSar":"Óptico + SAR","biTemporal":"Bi-temporal","advanced":"Avançado","image":"IMAGEM","opticalImage":"IMAGEM ÓPTICA","sarImage":"IMAGEM SAR","beforeImage":"IMAGEM ANTES","afterImage":"IMAGEM DEPOIS","uploadDesc":"Arraste e solte ou clique para enviar","uploadFormats":"GeoTIFF · TIFF · PNG · JPEG · Máx 2GB","disasterType":"TIPO DE DESASTRE","targetClasses":"CLASSES ALVO","selectAll":"Selecionar tudo","deselectAll":"Desselecionar tudo","disasterQuery":"CONSULTA DE DESASTRE","optionalQuery":"CONSULTA OPCIONAL","askSatquery":"PERGUNTAR AO SATQUERY","queryPlaceholderDisaster":"ex. Detectar áreas afetadas por deslizamentos...","queryPlaceholderDetection":"ex. Detectar edifícios e veículos...","queryPlaceholderGeneral":"Faça uma pergunta sobre sua imagem de satélite...","suggestions":"SUGESTÕES","analyzeDisaster":"Analisar desastre","detectObjects":"Detectar objetos","analyzeQuery":"Analisar consulta","analyzingDisaster":"Analisando desastre…","detecting":"Detectando…","analyzing":"Analisando…","viewer":"VISUALIZADOR DE IMAGEM DE SATÉLITE","showOverlays":"Mostrar sobreposições","hideOverlays":"Ocultar sobreposições","lat":"LAT","lon":"LON","zoom":"ZOOM","resolution":"RESOLUÇÃO","mode":"MODO","detections":"DETECÇÕES","disaster":"DESASTRE","severity":"SEVERIDADE","affectedArea":"ÁREA AFETADA","agentTrace":"RASTREAMENTO DE EXECUÇÃO DO AGENTE","uploadImageFirst":"Carregue imagens e insira uma consulta para iniciar a análise","selectClassesFirst":"Selecione as classes alvo e clique em Detectar objetos","selectDisasterFirst":"Selecione o tipo de desastre e clique em Analisar desastre","processingMetadata":"Processando metadados…"},
        "results": {"title":"Resultados da análise","objectsDetected":"objetos","confidence":"Confiança","loading":"Carregando módulo..."},
        "common": {"online":"online","offline":"offline","error":"Algo deu errado","success":"Sucesso","warning":"Aviso","search":"Pesquisar idioma..."}
    },
    "it": {
        "nav": {"overview":"Panoramica","workspace":"Area di lavoro","results":"Risultati","history":"Cronologia analisi","models":"Modelli e strumenti","datasets":"Set di dati","reports":"Rapporti","settings":"Impostazioni","navigation":"NAVIGAZIONE","systemStatus":"STATO SISTEMA","aiEngine":"Motore AI","geoPipeline":"Pipeline geospaziale","dataLink":"Collegamento dati","analyst":"Analista","systemOnline":"SISTEMA ONLINE","syncAgo":"SINCRONIZZATO 0m FA","utc":"UTC"},
        "workspace": {"title":"Area di lavoro di analisi","ready":"MOTORE DI INFERENZA AI: PRONTO","singleImage":"Immagine singola","objectDetection":"Rilevamento oggetti","disasterAnalysis":"Analisi disastri","opticalSar":"Ottico + SAR","biTemporal":"Bi-temporale","advanced":"Avanzato","image":"IMMAGINE","opticalImage":"IMMAGINE OTTICA","sarImage":"IMMAGINE SAR","beforeImage":"IMMAGINE PRIMA","afterImage":"IMMAGINE DOPO","uploadDesc":"Trascina e rilascia o clicca per caricare","uploadFormats":"GeoTIFF · TIFF · PNG · JPEG · Max 2GB","disasterType":"TIPO DISASTRO","targetClasses":"CLASSI TARGET","selectAll":"Seleziona tutto","deselectAll":"Deseleziona tutto","disasterQuery":"QUERY DISASTRO","optionalQuery":"QUERY OPZIONALE","askSatquery":"CHIEDI A SATQUERY","queryPlaceholderDisaster":"es. Rileva le aree colpite da frane...","queryPlaceholderDetection":"es. Rileva edifici e veicoli...","queryPlaceholderGeneral":"Fai una domanda sulla tua immagine satellitare...","suggestions":"SUGGERIMENTI","analyzeDisaster":"Analizza disastro","detectObjects":"Rileva oggetti","analyzeQuery":"Analizza query","analyzingDisaster":"Analisi disastro in corso…","detecting":"Rilevamento in corso…","analyzing":"Analisi in corso…","viewer":"VISUALIZZATORE IMMAGINE SATELLITARE","showOverlays":"Mostra overlay","hideOverlays":"Nascondi overlay","lat":"LAT","lon":"LON","zoom":"ZOOM","resolution":"RISOLUZIONE","mode":"MODALITÀ","detections":"RILEVAMENTI","disaster":"DISASTRO","severity":"GRAVITÀ","affectedArea":"AREA COLPITA","agentTrace":"TRACCIA ESECUZIONE AGENTE","uploadImageFirst":"Carica immagini e inserisci una query per iniziare l'analisi","selectClassesFirst":"Seleziona le classi target e clicca su Rileva oggetti","selectDisasterFirst":"Seleziona il tipo di disastro e clicca su Analizza disastro","processingMetadata":"Elaborazione metadati…"},
        "results": {"title":"Risultati analisi","objectsDetected":"oggetti","confidence":"Confidenza","loading":"Caricamento modulo..."},
        "common": {"online":"online","offline":"offline","error":"Qualcosa è andato storto","success":"Successo","warning":"Avviso","search":"Cerca lingua..."}
    },
    "nl": {
        "nav": {"overview":"Overzicht","workspace":"Werkruimte","results":"Resultaten","history":"Analysegeschiedenis","models":"Modellen en tools","datasets":"Datasets","reports":"Rapporten","settings":"Instellingen","navigation":"NAVIGATIE","systemStatus":"SYSTEEMSTATUS","aiEngine":"AI-motor","geoPipeline":"Geo-pijplijn","dataLink":"Gegevenslink","analyst":"Analist","systemOnline":"SYSTEEM ONLINE","syncAgo":"0m GELEDEN GESYNCHRONISEERD","utc":"UTC"},
        "workspace": {"title":"Analysewerkruimte","ready":"AI-INFERENTIEMOTOR: GEREED","singleImage":"Enkele afbeelding","objectDetection":"Objectdetectie","disasterAnalysis":"Rampenanalyse","opticalSar":"Optisch + SAR","biTemporal":"Bi-temporeel","advanced":"Geavanceerd","image":"AFBEELDING","opticalImage":"OPTISCHE AFBEELDING","sarImage":"SAR-AFBEELDING","beforeImage":"AFBEELDING VOOR","afterImage":"AFBEELDING NA","uploadDesc":"Slepen en neerzetten of klikken om te uploaden","uploadFormats":"GeoTIFF · TIFF · PNG · JPEG · Max 2GB","disasterType":"RAMPTYPE","targetClasses":"DOELKLASSEN","selectAll":"Alles selecteren","deselectAll":"Alles deselecteren","disasterQuery":"RAMPENQUERY","optionalQuery":"OPTIONELE QUERY","askSatquery":"SATQUERY VRAGEN","queryPlaceholderDisaster":"bijv. Detecteer door aardverschuivingen getroffen gebieden...","queryPlaceholderDetection":"bijv. Detecteer gebouwen en voertuigen...","queryPlaceholderGeneral":"Stel een vraag over uw satellietafbeelding...","suggestions":"SUGGESTIES","analyzeDisaster":"Ramp analyseren","detectObjects":"Objecten detecteren","analyzeQuery":"Query analyseren","analyzingDisaster":"Rampenanalyse bezig…","detecting":"Detectie bezig…","analyzing":"Analyse bezig…","viewer":"SATELLIETBEELDVIEWER","showOverlays":"Overlays weergeven","hideOverlays":"Overlays verbergen","lat":"BRD","lon":"LNG","zoom":"ZOOM","resolution":"RESOLUTIE","mode":"MODUS","detections":"DETECTIES","disaster":"RAMP","severity":"ERNST","affectedArea":"GETROFFEN GEBIED","agentTrace":"AGENT-UITVOERINGSLOG","uploadImageFirst":"Upload afbeeldingen en voer een query in om de analyse te starten","selectClassesFirst":"Selecteer doelklassen en klik op Objecten detecteren","selectDisasterFirst":"Selecteer het ramptype en klik op Ramp analyseren","processingMetadata":"Metagegevens worden verwerkt…"},
        "results": {"title":"Analyseresultaten","objectsDetected":"objecten","confidence":"Vertrouwen","loading":"Module laden..."},
        "common": {"online":"online","offline":"offline","error":"Er is iets misgegaan","success":"Succes","warning":"Waarschuwing","search":"Taal zoeken..."}
    },
    "ru": {
        "nav": {"overview":"Обзор","workspace":"Рабочее пространство","results":"Результаты","history":"История анализа","models":"Модели и инструменты","datasets":"Наборы данных","reports":"Отчёты","settings":"Настройки","navigation":"НАВИГАЦИЯ","systemStatus":"СТАТУС СИСТЕМЫ","aiEngine":"Движок ИИ","geoPipeline":"Геопайплайн","dataLink":"Канал данных","analyst":"Аналитик","systemOnline":"СИСТЕМА В СЕТИ","syncAgo":"СИНХРОНИЗИРОВАНО 0м НАЗАД","utc":"UTC"},
        "workspace": {"title":"Рабочее пространство анализа","ready":"ДВИЖОК ВЫВОДА ИИ: ГОТОВ","singleImage":"Одиночное изображение","objectDetection":"Обнаружение объектов","disasterAnalysis":"Анализ катастроф","opticalSar":"Оптика + РСА","biTemporal":"Двухвременной","advanced":"Расширенный","image":"ИЗОБРАЖЕНИЕ","opticalImage":"ОПТИЧЕСКОЕ ИЗОБРАЖЕНИЕ","sarImage":"РСА-ИЗОБРАЖЕНИЕ","beforeImage":"ИЗОБРАЖЕНИЕ ДО","afterImage":"ИЗОБРАЖЕНИЕ ПОСЛЕ","uploadDesc":"Перетащите или нажмите для загрузки","uploadFormats":"GeoTIFF · TIFF · PNG · JPEG · Макс. 2ГБ","disasterType":"ТИП КАТАСТРОФЫ","targetClasses":"ЦЕЛЕВЫЕ КЛАССЫ","selectAll":"Выбрать всё","deselectAll":"Снять всё","disasterQuery":"ЗАПРОС ПО КАТАСТРОФЕ","optionalQuery":"НЕОБЯЗАТЕЛЬНЫЙ ЗАПРОС","askSatquery":"СПРОСИТЬ SATQUERY","queryPlaceholderDisaster":"напр. Обнаружить районы, пострадавшие от оползней...","queryPlaceholderDetection":"напр. Обнаружить здания и транспортные средства...","queryPlaceholderGeneral":"Задайте вопрос о вашем спутниковом снимке...","suggestions":"ПОДСКАЗКИ","analyzeDisaster":"Анализировать катастрофу","detectObjects":"Обнаружить объекты","analyzeQuery":"Анализировать запрос","analyzingDisaster":"Анализ катастрофы выполняется…","detecting":"Обнаружение выполняется…","analyzing":"Анализ выполняется…","viewer":"ПРОСМОТРЩИК СПУТНИКОВЫХ СНИМКОВ","showOverlays":"Показать наложения","hideOverlays":"Скрыть наложения","lat":"ШИР","lon":"ДОЛ","zoom":"МАСШТАБ","resolution":"РАЗРЕШЕНИЕ","mode":"РЕЖИМ","detections":"ОБНАРУЖЕНИЯ","disaster":"КАТАСТРОФА","severity":"СЕРЬЁЗНОСТЬ","affectedArea":"ПОРАЖЁННАЯ ПЛОЩАДЬ","agentTrace":"ЖУРНАЛ ВЫПОЛНЕНИЯ АГЕНТА","uploadImageFirst":"Загрузите изображения и введите запрос для начала анализа","selectClassesFirst":"Выберите целевые классы и нажмите «Обнаружить объекты»","selectDisasterFirst":"Выберите тип катастрофы и нажмите «Анализировать катастрофу»","processingMetadata":"Обработка метаданных…"},
        "results": {"title":"Результаты анализа","objectsDetected":"объекты","confidence":"Уверенность","loading":"Загрузка модуля..."},
        "common": {"online":"в сети","offline":"не в сети","error":"Что-то пошло не так","success":"Успех","warning":"Предупреждение","search":"Поиск языка..."}
    },
    "uk": {
        "nav": {"overview":"Огляд","workspace":"Робочий простір","results":"Результати","history":"Історія аналізу","models":"Моделі та інструменти","datasets":"Набори даних","reports":"Звіти","settings":"Налаштування","navigation":"НАВІГАЦІЯ","systemStatus":"СТАТУС СИСТЕМИ","aiEngine":"Двигун ШІ","geoPipeline":"Геопайплайн","dataLink":"Канал даних","analyst":"Аналітик","systemOnline":"СИСТЕМА В МЕРЕЖІ","syncAgo":"СИНХРОНІЗОВАНО 0хв ТОМУ","utc":"UTC"},
        "workspace": {"title":"Робочий простір аналізу","ready":"ДВИГУН ВИВОДУ ШІ: ГОТОВИЙ","singleImage":"Одне зображення","objectDetection":"Виявлення об'єктів","disasterAnalysis":"Аналіз катастроф","opticalSar":"Оптика + РСА","biTemporal":"Двочасовий","advanced":"Розширений","image":"ЗОБРАЖЕННЯ","opticalImage":"ОПТИЧНЕ ЗОБРАЖЕННЯ","sarImage":"РСА-ЗОБРАЖЕННЯ","beforeImage":"ЗОБРАЖЕННЯ ДО","afterImage":"ЗОБРАЖЕННЯ ПІСЛЯ","uploadDesc":"Перетягніть або натисніть для завантаження","uploadFormats":"GeoTIFF · TIFF · PNG · JPEG · Макс. 2ГБ","disasterType":"ТИП КАТАСТРОФИ","targetClasses":"ЦІЛЬОВІ КЛАСИ","selectAll":"Вибрати все","deselectAll":"Зняти все","disasterQuery":"ЗАПИТ ПО КАТАСТРОФІ","optionalQuery":"НЕОБОВ'ЯЗКОВИЙ ЗАПИТ","askSatquery":"ЗАПИТАТИ SATQUERY","queryPlaceholderDisaster":"напр. Виявити райони, постраждалі від зсувів...","queryPlaceholderDetection":"напр. Виявити будівлі та транспортні засоби...","queryPlaceholderGeneral":"Поставте запитання про ваш супутниковий знімок...","suggestions":"ПІДКАЗКИ","analyzeDisaster":"Аналізувати катастрофу","detectObjects":"Виявити об'єкти","analyzeQuery":"Аналізувати запит","analyzingDisaster":"Аналіз катастрофи виконується…","detecting":"Виявлення виконується…","analyzing":"Аналіз виконується…","viewer":"ПЕРЕГЛЯДАЧ СУПУТНИКОВИХ ЗНІМКІВ","showOverlays":"Показати накладання","hideOverlays":"Приховати накладання","lat":"ШИР","lon":"ДОВ","zoom":"МАСШТАБ","resolution":"РОЗДІЛЬНІСТЬ","mode":"РЕЖИМ","detections":"ВИЯВЛЕННЯ","disaster":"КАТАСТРОФА","severity":"СЕРЙОЗНІСТЬ","affectedArea":"ПОСТРАЖДАЛА ПЛОЩА","agentTrace":"ЖУРНАЛ ВИКОНАННЯ АГЕНТА","uploadImageFirst":"Завантажте зображення та введіть запит для початку аналізу","selectClassesFirst":"Виберіть цільові класи та натисніть «Виявити об'єкти»","selectDisasterFirst":"Виберіть тип катастрофи та натисніть «Аналізувати катастрофу»","processingMetadata":"Обробка метаданих…"},
        "results": {"title":"Результати аналізу","objectsDetected":"об'єкти","confidence":"Впевненість","loading":"Завантаження модуля..."},
        "common": {"online":"в мережі","offline":"не в мережі","error":"Щось пішло не так","success":"Успіх","warning":"Попередження","search":"Пошук мови..."}
    },
    "zh-CN": {
        "nav": {"overview":"概览","workspace":"分析工作区","results":"结果","history":"分析历史","models":"模型与工具","datasets":"数据集","reports":"报告","settings":"设置","navigation":"导航","systemStatus":"系统状态","aiEngine":"AI引擎","geoPipeline":"地理管道","dataLink":"数据链接","analyst":"分析师","systemOnline":"系统在线","syncAgo":"0分钟前同步","utc":"UTC"},
        "workspace": {"title":"分析工作区","ready":"AI推理引擎：就绪","singleImage":"单图像","objectDetection":"目标检测","disasterAnalysis":"灾害分析","opticalSar":"光学+SAR","biTemporal":"双时相","advanced":"高级","image":"图像","opticalImage":"光学图像","sarImage":"SAR图像","beforeImage":"前图像","afterImage":"后图像","uploadDesc":"拖放或点击上传","uploadFormats":"GeoTIFF · TIFF · PNG · JPEG · 最大2GB","disasterType":"灾害类型","targetClasses":"目标类别","selectAll":"全选","deselectAll":"取消全选","disasterQuery":"灾害查询","optionalQuery":"可选查询","askSatquery":"询问SatQuery","queryPlaceholderDisaster":"例：检测滑坡影响区域...","queryPlaceholderDetection":"例：检测建筑物和车辆...","queryPlaceholderGeneral":"询问关于卫星图像的问题...","suggestions":"建议","analyzeDisaster":"分析灾害","detectObjects":"检测目标","analyzeQuery":"分析查询","analyzingDisaster":"灾害分析中…","detecting":"检测中…","analyzing":"分析中…","viewer":"卫星图像查看器","showOverlays":"显示叠加层","hideOverlays":"隐藏叠加层","lat":"纬度","lon":"经度","zoom":"缩放","resolution":"分辨率","mode":"模式","detections":"检测","disaster":"灾害","severity":"严重性","affectedArea":"受影响面积","agentTrace":"代理执行轨迹","uploadImageFirst":"上传图像并输入查询以开始分析","selectClassesFirst":"选择目标类别并点击检测目标","selectDisasterFirst":"选择灾害类型并点击分析灾害","processingMetadata":"正在处理元数据…"},
        "results": {"title":"分析结果","objectsDetected":"个目标","confidence":"置信度","loading":"加载模块中..."},
        "common": {"online":"在线","offline":"离线","error":"出现错误","success":"成功","warning":"警告","search":"搜索语言..."}
    },
    "zh-TW": {
        "nav": {"overview":"概覽","workspace":"分析工作區","results":"結果","history":"分析歷史","models":"模型與工具","datasets":"資料集","reports":"報告","settings":"設定","navigation":"導航","systemStatus":"系統狀態","aiEngine":"AI引擎","geoPipeline":"地理管道","dataLink":"資料連結","analyst":"分析師","systemOnline":"系統上線","syncAgo":"0分鐘前同步","utc":"UTC"},
        "workspace": {"title":"分析工作區","ready":"AI推理引擎：就緒","singleImage":"單一影像","objectDetection":"目標偵測","disasterAnalysis":"災害分析","opticalSar":"光學+SAR","biTemporal":"雙時相","advanced":"進階","image":"影像","opticalImage":"光學影像","sarImage":"SAR影像","beforeImage":"前影像","afterImage":"後影像","uploadDesc":"拖放或點擊上傳","uploadFormats":"GeoTIFF · TIFF · PNG · JPEG · 最大2GB","disasterType":"災害類型","targetClasses":"目標類別","selectAll":"全選","deselectAll":"取消全選","disasterQuery":"災害查詢","optionalQuery":"可選查詢","askSatquery":"詢問SatQuery","queryPlaceholderDisaster":"例：偵測滑坡影響區域...","queryPlaceholderDetection":"例：偵測建築物和車輛...","queryPlaceholderGeneral":"詢問關於衛星影像的問題...","suggestions":"建議","analyzeDisaster":"分析災害","detectObjects":"偵測目標","analyzeQuery":"分析查詢","analyzingDisaster":"災害分析中…","detecting":"偵測中…","analyzing":"分析中…","viewer":"衛星影像檢視器","showOverlays":"顯示疊加層","hideOverlays":"隱藏疊加層","lat":"緯度","lon":"經度","zoom":"縮放","resolution":"解析度","mode":"模式","detections":"偵測","disaster":"災害","severity":"嚴重性","affectedArea":"受影響面積","agentTrace":"代理執行軌跡","uploadImageFirst":"上傳影像並輸入查詢以開始分析","selectClassesFirst":"選擇目標類別並點擊偵測目標","selectDisasterFirst":"選擇災害類型並點擊分析災害","processingMetadata":"正在處理元數據…"},
        "results": {"title":"分析結果","objectsDetected":"個目標","confidence":"置信度","loading":"載入模組中..."},
        "common": {"online":"上線","offline":"離線","error":"發生錯誤","success":"成功","warning":"警告","search":"搜尋語言..."}
    },
    "ja": {
        "nav": {"overview":"概要","workspace":"分析ワークスペース","results":"結果","history":"分析履歴","models":"モデルとツール","datasets":"データセット","reports":"レポート","settings":"設定","navigation":"ナビゲーション","systemStatus":"システム状態","aiEngine":"AIエンジン","geoPipeline":"ジオパイプライン","dataLink":"データリンク","analyst":"アナリスト","systemOnline":"システムオンライン","syncAgo":"0分前に同期","utc":"UTC"},
        "workspace": {"title":"分析ワークスペース","ready":"AI推論エンジン：準備完了","singleImage":"単一画像","objectDetection":"物体検出","disasterAnalysis":"災害分析","opticalSar":"光学+SAR","biTemporal":"バイテンポラル","advanced":"高度","image":"画像","opticalImage":"光学画像","sarImage":"SAR画像","beforeImage":"前の画像","afterImage":"後の画像","uploadDesc":"ドラッグ＆ドロップまたはクリックしてアップロード","uploadFormats":"GeoTIFF · TIFF · PNG · JPEG · 最大2GB","disasterType":"災害タイプ","targetClasses":"ターゲットクラス","selectAll":"すべて選択","deselectAll":"すべて選択解除","disasterQuery":"災害クエリ","optionalQuery":"オプションクエリ","askSatquery":"SatQueryに質問","queryPlaceholderDisaster":"例：地滑り影響地域を検出...","queryPlaceholderDetection":"例：建物と車両を検出...","queryPlaceholderGeneral":"衛星画像について質問してください...","suggestions":"提案","analyzeDisaster":"災害を分析","detectObjects":"物体を検出","analyzeQuery":"クエリを分析","analyzingDisaster":"災害分析中…","detecting":"検出中…","analyzing":"分析中…","viewer":"衛星画像ビューアー","showOverlays":"オーバーレイを表示","hideOverlays":"オーバーレイを非表示","lat":"緯度","lon":"経度","zoom":"ズーム","resolution":"解像度","mode":"モード","detections":"検出","disaster":"災害","severity":"深刻度","affectedArea":"影響面積","agentTrace":"エージェント実行トレース","uploadImageFirst":"分析を開始するには画像をアップロードしてクエリを入力してください","selectClassesFirst":"ターゲットクラスを選択して物体を検出をクリックしてください","selectDisasterFirst":"災害タイプを選択して災害を分析をクリックしてください","processingMetadata":"メタデータを処理中…"},
        "results": {"title":"分析結果","objectsDetected":"オブジェクト","confidence":"信頼度","loading":"モジュール読み込み中..."},
        "common": {"online":"オンライン","offline":"オフライン","error":"エラーが発生しました","success":"成功","warning":"警告","search":"言語を検索..."}
    },
    "ko": {
        "nav": {"overview":"개요","workspace":"분석 작업 공간","results":"결과","history":"분석 기록","models":"모델 및 도구","datasets":"데이터셋","reports":"보고서","settings":"설정","navigation":"내비게이션","systemStatus":"시스템 상태","aiEngine":"AI 엔진","geoPipeline":"지오 파이프라인","dataLink":"데이터 링크","analyst":"분석가","systemOnline":"시스템 온라인","syncAgo":"0분 전 동기화","utc":"UTC"},
        "workspace": {"title":"분석 작업 공간","ready":"AI 추론 엔진: 준비됨","singleImage":"단일 이미지","objectDetection":"객체 감지","disasterAnalysis":"재난 분석","opticalSar":"광학 + SAR","biTemporal":"이중 시간","advanced":"고급","image":"이미지","opticalImage":"광학 이미지","sarImage":"SAR 이미지","beforeImage":"이전 이미지","afterImage":"이후 이미지","uploadDesc":"드래그 앤 드롭하거나 클릭하여 업로드","uploadFormats":"GeoTIFF · TIFF · PNG · JPEG · 최대 2GB","disasterType":"재난 유형","targetClasses":"대상 클래스","selectAll":"모두 선택","deselectAll":"모두 해제","disasterQuery":"재난 쿼리","optionalQuery":"선택적 쿼리","askSatquery":"SatQuery에 질문","queryPlaceholderDisaster":"예: 산사태 영향 지역 감지...","queryPlaceholderDetection":"예: 건물 및 차량 감지...","queryPlaceholderGeneral":"위성 이미지에 대해 질문하세요...","suggestions":"제안","analyzeDisaster":"재난 분석","detectObjects":"객체 감지","analyzeQuery":"쿼리 분석","analyzingDisaster":"재난 분석 중…","detecting":"감지 중…","analyzing":"분석 중…","viewer":"위성 이미지 뷰어","showOverlays":"오버레이 표시","hideOverlays":"오버레이 숨기기","lat":"위도","lon":"경도","zoom":"줌","resolution":"해상도","mode":"모드","detections":"감지","disaster":"재난","severity":"심각도","affectedArea":"영향 면적","agentTrace":"에이전트 실행 추적","uploadImageFirst":"분석을 시작하려면 이미지를 업로드하고 쿼리를 입력하세요","selectClassesFirst":"대상 클래스를 선택하고 객체 감지를 클릭하세요","selectDisasterFirst":"재난 유형을 선택하고 재난 분석을 클릭하세요","processingMetadata":"메타데이터 처리 중…"},
        "results": {"title":"분석 결과","objectsDetected":"객체","confidence":"신뢰도","loading":"모듈 로딩 중..."},
        "common": {"online":"온라인","offline":"오프라인","error":"오류가 발생했습니다","success":"성공","warning":"경고","search":"언어 검색..."}
    },
    "ar": {
        "nav": {"overview":"نظرة عامة","workspace":"مساحة عمل التحليل","results":"النتائج","history":"سجل التحليل","models":"النماذج والأدوات","datasets":"مجموعات البيانات","reports":"التقارير","settings":"الإعدادات","navigation":"التنقل","systemStatus":"حالة النظام","aiEngine":"محرك الذكاء الاصطناعي","geoPipeline":"خط أنابيب جغرافي","dataLink":"رابط البيانات","analyst":"محلل","systemOnline":"النظام متصل","syncAgo":"تزامن منذ 0 دقيقة","utc":"UTC"},
        "workspace": {"title":"مساحة عمل التحليل","ready":"محرك استدلال الذكاء الاصطناعي: جاهز","singleImage":"صورة واحدة","objectDetection":"اكتشاف الأجسام","disasterAnalysis":"تحليل الكوارث","opticalSar":"بصري + SAR","biTemporal":"ثنائي الزمن","advanced":"متقدم","image":"الصورة","opticalImage":"الصورة البصرية","sarImage":"صورة SAR","beforeImage":"الصورة قبل","afterImage":"الصورة بعد","uploadDesc":"اسحب وأفلت أو انقر للرفع","uploadFormats":"GeoTIFF · TIFF · PNG · JPEG · الحد الأقصى 2GB","disasterType":"نوع الكارثة","targetClasses":"الفئات المستهدفة","selectAll":"تحديد الكل","deselectAll":"إلغاء تحديد الكل","disasterQuery":"استعلام الكارثة","optionalQuery":"استعلام اختياري","askSatquery":"اسأل SatQuery","queryPlaceholderDisaster":"مثال: اكتشف المناطق المتضررة من الانزلاق الأرضي...","queryPlaceholderDetection":"مثال: اكتشف المباني والمركبات...","queryPlaceholderGeneral":"اطرح سؤالاً حول صورتك الفضائية...","suggestions":"اقتراحات","analyzeDisaster":"تحليل الكارثة","detectObjects":"اكتشاف الأجسام","analyzeQuery":"تحليل الاستعلام","analyzingDisaster":"جاري تحليل الكارثة…","detecting":"جاري الاكتشاف…","analyzing":"جاري التحليل…","viewer":"عارض الصور الفضائية","showOverlays":"إظهار الطبقات","hideOverlays":"إخفاء الطبقات","lat":"خط العرض","lon":"خط الطول","zoom":"تكبير","resolution":"الدقة","mode":"الوضع","detections":"الاكتشافات","disaster":"كارثة","severity":"الشدة","affectedArea":"المنطقة المتضررة","agentTrace":"تتبع تنفيذ الوكيل","uploadImageFirst":"ارفع الصور وأدخل استعلاماً لبدء التحليل","selectClassesFirst":"حدد الفئات المستهدفة وانقر على اكتشاف الأجسام","selectDisasterFirst":"حدد نوع الكارثة وانقر على تحليل الكارثة","processingMetadata":"جاري معالجة البيانات الوصفية…"},
        "results": {"title":"نتائج التحليل","objectsDetected":"أجسام","confidence":"الثقة","loading":"جاري تحميل الوحدة..."},
        "common": {"online":"متصل","offline":"غير متصل","error":"حدث خطأ ما","success":"نجاح","warning":"تحذير","search":"ابحث عن لغة..."}
    },
    "tr": {
        "nav": {"overview":"Genel Bakış","workspace":"Analiz Çalışma Alanı","results":"Sonuçlar","history":"Analiz Geçmişi","models":"Modeller ve Araçlar","datasets":"Veri Setleri","reports":"Raporlar","settings":"Ayarlar","navigation":"NAVİGASYON","systemStatus":"SİSTEM DURUMU","aiEngine":"AI Motoru","geoPipeline":"Coğrafi Boru Hattı","dataLink":"Veri Bağlantısı","analyst":"Analist","systemOnline":"SİSTEM ÇEVRİMİÇİ","syncAgo":"0d ÖNCE EŞLEME","utc":"UTC"},
        "workspace": {"title":"Analiz Çalışma Alanı","ready":"AI ÇIKARIM MOTORU: HAZIR","singleImage":"Tek Görüntü","objectDetection":"Nesne Tespiti","disasterAnalysis":"Afet Analizi","opticalSar":"Optik + SAR","biTemporal":"Çift Zamanlı","advanced":"Gelişmiş","image":"GÖRÜNTÜ","opticalImage":"OPTİK GÖRÜNTÜ","sarImage":"SAR GÖRÜNTÜSÜ","beforeImage":"ÖNCEKİ GÖRÜNTÜ","afterImage":"SONRAKİ GÖRÜNTÜ","uploadDesc":"Sürükleyin ve bırakın veya yüklemek için tıklayın","uploadFormats":"GeoTIFF · TIFF · PNG · JPEG · Maks. 2GB","disasterType":"AFET TÜRÜ","targetClasses":"HEDEF SINIFLAR","selectAll":"Tümünü Seç","deselectAll":"Tümünü Kaldır","disasterQuery":"AFET SORGUSU","optionalQuery":"İSTEĞE BAĞLI SORGU","askSatquery":"SATQUERY'YE SOR","queryPlaceholderDisaster":"örn. Heyelan etkilenen bölgeleri tespit et...","queryPlaceholderDetection":"örn. Binaları ve araçları tespit et...","queryPlaceholderGeneral":"Uydu görüntünüz hakkında soru sorun...","suggestions":"ÖNERİLER","analyzeDisaster":"Afeti Analiz Et","detectObjects":"Nesneleri Tespit Et","analyzeQuery":"Sorguyu Analiz Et","analyzingDisaster":"Afet analizi yapılıyor…","detecting":"Tespit yapılıyor…","analyzing":"Analiz yapılıyor…","viewer":"UYDU GÖRÜNTÜ GÖRÜNTÜLEYICI","showOverlays":"Katmanları Göster","hideOverlays":"Katmanları Gizle","lat":"ENLEM","lon":"BOYLAM","zoom":"ZOOM","resolution":"ÇÖZÜNÜRLÜK","mode":"MOD","detections":"TESPİTLER","disaster":"AFET","severity":"ŞİDDET","affectedArea":"ETKİLENEN ALAN","agentTrace":"AJAN YÜRÜTME İZİ","uploadImageFirst":"Analize başlamak için görüntü yükleyin ve sorgu girin","selectClassesFirst":"Hedef sınıfları seçin ve Nesneleri Tespit Et'e tıklayın","selectDisasterFirst":"Afet türünü seçin ve Afeti Analiz Et'e tıklayın","processingMetadata":"Meta veriler işleniyor…"},
        "results": {"title":"Analiz Sonuçları","objectsDetected":"nesne","confidence":"Güven","loading":"Modül yükleniyor..."},
        "common": {"online":"çevrimiçi","offline":"çevrimdışı","error":"Bir şeyler yanlış gitti","success":"Başarı","warning":"Uyarı","search":"Dil ara..."}
    },
    "id": {
        "nav": {"overview":"Gambaran Umum","workspace":"Ruang Kerja Analisis","results":"Hasil","history":"Riwayat Analisis","models":"Model & Alat","datasets":"Dataset","reports":"Laporan","settings":"Pengaturan","navigation":"NAVIGASI","systemStatus":"STATUS SISTEM","aiEngine":"Mesin AI","geoPipeline":"Pipeline Geo","dataLink":"Tautan Data","analyst":"Analis","systemOnline":"SISTEM ONLINE","syncAgo":"DISINKRONKAN 0m LALU","utc":"UTC"},
        "workspace": {"title":"Ruang Kerja Analisis","ready":"MESIN INFERENSI AI: SIAP","singleImage":"Gambar Tunggal","objectDetection":"Deteksi Objek","disasterAnalysis":"Analisis Bencana","opticalSar":"Optik + SAR","biTemporal":"Bi-Temporal","advanced":"Lanjutan","image":"GAMBAR","opticalImage":"GAMBAR OPTIK","sarImage":"GAMBAR SAR","beforeImage":"GAMBAR SEBELUM","afterImage":"GAMBAR SESUDAH","uploadDesc":"Seret & lepas atau klik untuk unggah","uploadFormats":"GeoTIFF · TIFF · PNG · JPEG · Maks 2GB","disasterType":"JENIS BENCANA","targetClasses":"KELAS TARGET","selectAll":"Pilih Semua","deselectAll":"Hapus Semua","disasterQuery":"KUERI BENCANA","optionalQuery":"KUERI OPSIONAL","askSatquery":"TANYA SATQUERY","queryPlaceholderDisaster":"mis. Deteksi area terdampak longsor...","queryPlaceholderDetection":"mis. Deteksi bangunan dan kendaraan...","queryPlaceholderGeneral":"Ajukan pertanyaan tentang citra satelit Anda...","suggestions":"SARAN","analyzeDisaster":"Analisis Bencana","detectObjects":"Deteksi Objek","analyzeQuery":"Analisis Kueri","analyzingDisaster":"Menganalisis bencana…","detecting":"Mendeteksi…","analyzing":"Menganalisis…","viewer":"PENAMPIL CITRA SATELIT","showOverlays":"Tampilkan Lapisan","hideOverlays":"Sembunyikan Lapisan","lat":"LAT","lon":"LON","zoom":"ZOOM","resolution":"RESOLUSI","mode":"MODE","detections":"DETEKSI","disaster":"BENCANA","severity":"KEPARAHAN","affectedArea":"AREA TERDAMPAK","agentTrace":"JEJAK EKSEKUSI AGEN","uploadImageFirst":"Unggah citra dan masukkan kueri untuk memulai analisis","selectClassesFirst":"Pilih kelas target dan klik Deteksi Objek","selectDisasterFirst":"Pilih jenis bencana dan klik Analisis Bencana","processingMetadata":"Memproses metadata…"},
        "results": {"title":"Hasil Analisis","objectsDetected":"objek","confidence":"Kepercayaan","loading":"Memuat modul..."},
        "common": {"online":"online","offline":"offline","error":"Terjadi kesalahan","success":"Berhasil","warning":"Peringatan","search":"Cari bahasa..."}
    },
    "vi": {
        "nav": {"overview":"Tổng quan","workspace":"Không gian làm việc phân tích","results":"Kết quả","history":"Lịch sử phân tích","models":"Mô hình & Công cụ","datasets":"Tập dữ liệu","reports":"Báo cáo","settings":"Cài đặt","navigation":"ĐIỀU HƯỚNG","systemStatus":"TRẠNG THÁI HỆ THỐNG","aiEngine":"Động cơ AI","geoPipeline":"Đường ống địa lý","dataLink":"Liên kết dữ liệu","analyst":"Nhà phân tích","systemOnline":"HỆ THỐNG TRỰC TUYẾN","syncAgo":"ĐỒNG BỘ CÁCH ĐÂY 0p","utc":"UTC"},
        "workspace": {"title":"Không gian làm việc phân tích","ready":"ĐỘNG CƠ SUY LUẬN AI: SẴN SÀNG","singleImage":"Ảnh đơn","objectDetection":"Phát hiện đối tượng","disasterAnalysis":"Phân tích thảm họa","opticalSar":"Quang học + SAR","biTemporal":"Hai thời điểm","advanced":"Nâng cao","image":"ẢNH","opticalImage":"ẢNH QUANG HỌC","sarImage":"ẢNH SAR","beforeImage":"ẢNH TRƯỚC","afterImage":"ẢNH SAU","uploadDesc":"Kéo thả hoặc nhấp để tải lên","uploadFormats":"GeoTIFF · TIFF · PNG · JPEG · Tối đa 2GB","disasterType":"LOẠI THẢM HỌA","targetClasses":"LỚP MỤC TIÊU","selectAll":"Chọn tất cả","deselectAll":"Bỏ chọn tất cả","disasterQuery":"TRUY VẤN THẢM HỌA","optionalQuery":"TRUY VẤN TÙY CHỌN","askSatquery":"HỎI SATQUERY","queryPlaceholderDisaster":"vd: Phát hiện vùng bị sạt lở...","queryPlaceholderDetection":"vd: Phát hiện tòa nhà và phương tiện...","queryPlaceholderGeneral":"Đặt câu hỏi về ảnh vệ tinh của bạn...","suggestions":"GỢI Ý","analyzeDisaster":"Phân tích thảm họa","detectObjects":"Phát hiện đối tượng","analyzeQuery":"Phân tích truy vấn","analyzingDisaster":"Đang phân tích thảm họa…","detecting":"Đang phát hiện…","analyzing":"Đang phân tích…","viewer":"TRÌNH XEM ẢNH VỆ TINH","showOverlays":"Hiện lớp phủ","hideOverlays":"Ẩn lớp phủ","lat":"VĨ ĐỘ","lon":"KINH ĐỘ","zoom":"THU PHÓNG","resolution":"ĐỘ PHÂN GIẢI","mode":"CHẾ ĐỘ","detections":"PHÁT HIỆN","disaster":"THẢM HỌA","severity":"MỨC ĐỘ","affectedArea":"DIỆN TÍCH ẢNH HƯỞNG","agentTrace":"DẤU VẾT THỰC THI AGENT","uploadImageFirst":"Tải ảnh lên và nhập truy vấn để bắt đầu phân tích","selectClassesFirst":"Chọn lớp mục tiêu và nhấp Phát hiện đối tượng","selectDisasterFirst":"Chọn loại thảm họa và nhấp Phân tích thảm họa","processingMetadata":"Đang xử lý siêu dữ liệu…"},
        "results": {"title":"Kết quả phân tích","objectsDetected":"đối tượng","confidence":"Độ tin cậy","loading":"Đang tải mô-đun..."},
        "common": {"online":"trực tuyến","offline":"ngoại tuyến","error":"Có lỗi xảy ra","success":"Thành công","warning":"Cảnh báo","search":"Tìm kiếm ngôn ngữ..."}
    },
    "th": {
        "nav": {"overview":"ภาพรวม","workspace":"พื้นที่ทำงานการวิเคราะห์","results":"ผลลัพธ์","history":"ประวัติการวิเคราะห์","models":"โมเดลและเครื่องมือ","datasets":"ชุดข้อมูล","reports":"รายงาน","settings":"การตั้งค่า","navigation":"การนำทาง","systemStatus":"สถานะระบบ","aiEngine":"เครื่องยนต์ AI","geoPipeline":"ไปป์ไลน์ทางภูมิศาสตร์","dataLink":"ลิงก์ข้อมูล","analyst":"นักวิเคราะห์","systemOnline":"ระบบออนไลน์","syncAgo":"ซิงค์เมื่อ 0 นาทีที่แล้ว","utc":"UTC"},
        "workspace": {"title":"พื้นที่ทำงานการวิเคราะห์","ready":"เครื่องยนต์การอนุมาน AI: พร้อม","singleImage":"ภาพเดี่ยว","objectDetection":"การตรวจจับวัตถุ","disasterAnalysis":"การวิเคราะห์ภัยพิบัติ","opticalSar":"ออปติคัล + SAR","biTemporal":"สองช่วงเวลา","advanced":"ขั้นสูง","image":"ภาพ","opticalImage":"ภาพออปติคัล","sarImage":"ภาพ SAR","beforeImage":"ภาพก่อน","afterImage":"ภาพหลัง","uploadDesc":"ลากและวางหรือคลิกเพื่ออัปโหลด","uploadFormats":"GeoTIFF · TIFF · PNG · JPEG · สูงสุด 2GB","disasterType":"ประเภทภัยพิบัติ","targetClasses":"คลาสเป้าหมาย","selectAll":"เลือกทั้งหมด","deselectAll":"ยกเลิกการเลือกทั้งหมด","disasterQuery":"คำค้นภัยพิบัติ","optionalQuery":"คำค้นเพิ่มเติม","askSatquery":"ถาม SatQuery","queryPlaceholderDisaster":"เช่น ตรวจจับพื้นที่ที่ได้รับผลกระทบจากดินโคลนถล่ม...","queryPlaceholderDetection":"เช่น ตรวจจับอาคารและยานพาหนะ...","queryPlaceholderGeneral":"ถามคำถามเกี่ยวกับภาพถ่ายดาวเทียมของคุณ...","suggestions":"คำแนะนำ","analyzeDisaster":"วิเคราะห์ภัยพิบัติ","detectObjects":"ตรวจจับวัตถุ","analyzeQuery":"วิเคราะห์คำค้น","analyzingDisaster":"กำลังวิเคราะห์ภัยพิบัติ…","detecting":"กำลังตรวจจับ…","analyzing":"กำลังวิเคราะห์…","viewer":"โปรแกรมดูภาพถ่ายดาวเทียม","showOverlays":"แสดงการซ้อนทับ","hideOverlays":"ซ่อนการซ้อนทับ","lat":"ละติจูด","lon":"ลองจิจูด","zoom":"ซูม","resolution":"ความละเอียด","mode":"โหมด","detections":"การตรวจจับ","disaster":"ภัยพิบัติ","severity":"ความรุนแรง","affectedArea":"พื้นที่ที่ได้รับผลกระทบ","agentTrace":"การติดตามการดำเนินการของตัวแทน","uploadImageFirst":"อัปโหลดภาพและป้อนคำค้นเพื่อเริ่มการวิเคราะห์","selectClassesFirst":"เลือกคลาสเป้าหมายและคลิกตรวจจับวัตถุ","selectDisasterFirst":"เลือกประเภทภัยพิบัติและคลิกวิเคราะห์ภัยพิบัติ","processingMetadata":"กำลังประมวลผลข้อมูลเมตา…"},
        "results": {"title":"ผลการวิเคราะห์","objectsDetected":"วัตถุ","confidence":"ความเชื่อมั่น","loading":"กำลังโหลดโมดูล..."},
        "common": {"online":"ออนไลน์","offline":"ออฟไลน์","error":"เกิดข้อผิดพลาดบางอย่าง","success":"สำเร็จ","warning":"คำเตือน","search":"ค้นหาภาษา..."}
    }
}

os.makedirs(locales_dir, exist_ok=True)

for lang_code, data in translations.items():
    out_file = os.path.join(locales_dir, f"{lang_code}.json")
    with open(out_file, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"Written: {lang_code}.json")

print("All done!")
